apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-tasks
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - wget
                - -q
                - -O
                - /dev/stdout
                - https://docs.zarantonello.dev/api/cron.daily?token=$(UTILS_SECRET)
              envFrom:
                - secretRef:
                    name: outline-env
              image: docker.io/library/busybox:1.37.0@sha256:ab33eacc8251e3807b85bb6dba570e4698c3998eca6f0fc2ccb60575a563ea74
              name: job
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          enableServiceLinks: false
          restartPolicy: Never
          securityContext:
            fsGroup: 32790
            runAsGroup: 32790
            runAsNonRoot: true
            runAsUser: 32790
            seccompProfile:
              type: RuntimeDefault
  schedule: 0 2 * * *
