networks:
  alloy_default:
    external: true
  traefik_default:
    external: true

services:
  victorialogs:
    cap_drop:
      - ALL
    command:
      # Logs occupy more space so we store them for a shorter amount of time.
      - -retentionPeriod=30d
    image: docker.io/victoriametrics/victoria-logs:v1.24.0-victorialogs-scratch@sha256:e17af6c23e420b33f15731bb974fef826b97349756a63e01fe37ddf054f863dd
    labels:
      monitoring.collect: true
      monitoring.metrics.port: 9428
      traefik.enable: true
      traefik.http.routers.victorialogs.entrypoints: http
      traefik.http.routers.victorialogs.rule: Host(`victorialogs.zarantonello.net`)
      traefik.http.services.victorialogs.loadbalancer.server.port: 9428
    networks:
      - traefik_default
      - alloy_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges=true
    user: 54433:54433
    volumes:
      - $HOME/volumes/victoriametrics/logs:/victoria-logs-data

  victoriametrics:
    cap_drop:
      - ALL
    command:
      # We don't injest many metrics so we can store them for a long time time
      # to be able to do long term analysis.
      - -retentionPeriod=180d
    image: docker.io/victoriametrics/victoria-metrics:v1.124.0-scratch@sha256:26cc0933f80f0ada58d1f5598ac4197fafdfd570e4b31e30b58fcabacf41cfe1
    labels:
      monitoring.collect: true
      monitoring.metrics.port: 8428
      traefik.enable: true
      traefik.http.routers.victoriametrics.entrypoints: http
      traefik.http.routers.victoriametrics.rule: Host(`victoriametrics.zarantonello.net`)
      traefik.http.services.victoriametrics.loadbalancer.server.port: 8428
    networks:
      - traefik_default
      - alloy_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges=true
    user: 34866:34866
    volumes:
      - $HOME/volumes/victoriametrics/metrics:/victoria-metrics-data
