apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: http-prem-1
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: 100.94.195.11
      lbipam.cilium.io/sharing-cross-namespace: "*"
      lbipam.cilium.io/sharing-key: prem-1-tailscale
  listeners:
    - allowedRoutes: &allowedRoutes
        namespaces:
          from: All
      name: http
      port: 80
      protocol: HTTP
    - allowedRoutes: *allowedRoutes
      name: https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          # https://github.com/cilium/cilium/issues/41228
          # - kind: Secret
          # name: zarantonello-dev-tls
          - kind: Secret
            name: zarantonello-net-tls
