apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: http-hetz-0
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: 100.64.0.1
      lbipam.cilium.io/sharing-cross-namespace: "*"
      lbipam.cilium.io/sharing-key: hetz-0-tailscale
  listeners:
    - allowedRoutes: &allowedRoutes
        namespaces:
          from: All
      name: http
      port: 80
      protocol: HTTP
    - allowedRoutes: *allowedRoutes
      hostname: "*.zarantonello.net"
      name: https-zarantonello-net
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - kind: Secret
            name: zarantonello-net-tls
    - allowedRoutes: *allowedRoutes
      hostname: "*.zarantonello.dev"
      name: https-zarantonello-dev
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - kind: Secret
            name: zarantonello-dev-tls
