apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5G
  local:
    path: /var/mnt/local-storage/minecraft-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - prem-1
