apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
  - files:
      - generated/configs/authelia.yaml
    name: authelia-config
kind: Kustomization
namespace: authelia
resources:
  - deployments/authelia.yaml
  - deployments/postgres.yaml
  - deployments/redis.yaml
  - namespace.yaml
  - persistent-volume-claims/postgres-data.yaml
  - persistent-volume-claims/redis-data.yaml
  - persistent-volumes/authelia-postgres-data.yaml
  - persistent-volumes/authelia-redis-data.yaml
  - service-accounts/default.yml
  - services/postgres.yaml
  - services/redis.yaml
  - services/web-ui.yaml
secretGenerator:
  - envs:
      - generated/secrets/authelia.env
    name: authelia-env
  - files:
      - generated/secrets/authelia-users.yaml
    name: authelia-users
  - envs:
      - generated/secrets/postgres.env
    name: postgres-env
