configs:
  grafana:
    file: ./grafana.ini

networks:
  traefik_default:
    external: true
  vmagent_default:
    external: true

services:
  init:
    cap_drop:
      - ALL
    command:
      - -c
      - |
        set -ex
        mkdir -p /var/lib/grafana/plugins/
        ver=$(curl -s https://api.github.com/repos/VictoriaMetrics/victoriametrics-datasource/releases/latest | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        curl -L https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/download/$$ver/victoriametrics-metrics-datasource-$$ver.tar.gz -o /var/lib/grafana/plugins/vm-plugin.tar.gz
        tar -xf /var/lib/grafana/plugins/vm-plugin.tar.gz -C /var/lib/grafana/plugins/
        rm /var/lib/grafana/plugins/vm-plugin.tar.gz
        ver=$(curl -s https://api.github.com/repos/VictoriaMetrics/victorialogs-datasource/releases/latest | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        curl -L https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/$$ver/victoriametrics-logs-datasource-$$ver.tar.gz -o /var/lib/grafana/plugins/vl-plugin.tar.gz
        tar -xf /var/lib/grafana/plugins/vl-plugin.tar.gz -C /var/lib/grafana/plugins/
        rm /var/lib/grafana/plugins/vl-plugin.tar.gz
    image: docker.io/curlimages/curl:7.85.0
    restart: "no"
    security_opt:
      - no-new-privileges:true
    user: 31904:31904
    volumes:
      - $HOME/volumes/grafana/data:/var/lib/grafana

  grafana:
    cap_drop:
      - ALL
    configs:
      - source: grafana
        target: /etc/grafana/grafana.ini
    depends_on:
      init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    env_file: .env
    image: docker.io/grafana/grafana:11.6.0@sha256:62d2b9d20a19714ebfe48d1bb405086081bc602aa053e28cf6d73c7537640dfb
    labels:
      traefik.enable: true
      traefik.http.routers.grafana.entrypoints: https
      traefik.http.routers.grafana.rule: Host(`grafana.zarantonello.net`)
      traefik.http.services.grafana.loadbalancer.server.port: 3000
      victoriametrics.job: grafana
      victoriametrics.port: 3000
    networks:
      - default
      - traefik_default
      - vmagent_default
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 31904:31904
    volumes:
      - ./provisioning:/etc/grafana/provisioning:z
      - $HOME/volumes/grafana/data:/var/lib/grafana

  postgres:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      # Configures the user used for healthchecking.
      PGUSER: ${POSTGRES_USER}
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - pg_isready
      timeout: 5s
    image: docker.io/library/postgres:17.4-alpine@sha256:7062a2109c4b51f3c792c7ea01e83ed12ef9a980886e3b3d380a7d2e5f6ce3f5
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=70,gid=70
      - /var/run/postgresql:uid=70,gid=70
    # User has to be 70, otherwise the container tries to chown the postgres
    # volume but fails due to insufficient permissions.
    user: 70:70
    volumes:
      - $HOME/volumes/grafana/postgres:/var/lib/postgresql/data
