# SETUP:
#
# Create a .env file with:
#
# - OIDC_CLIENT_ID
# - OIDC_CLIENT_SECRET
# - POSTGRES_DB
# - POSTGRES_PASSWORD
# - POSTGRES_USER
# - SECRET_KEY
# - SMTP_PASSWORD
# - SMTP_USERNAME
# - UTILS_SECRET

networks:
  traefik_default:
    external: true

services:
  outline:
    cap_drop:
      - ALL
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE}
      FILE_STORAGE: local
      OIDC_AUTH_URI: https://auth.zarantonello.dev/api/oidc/authorization
      OIDC_DISABLE_REDIRECT: true
      OIDC_DISPLAY_NAME: Authelia
      OIDC_TOKEN_URI: https://auth.zarantonello.dev/api/oidc/token
      OIDC_USERINFO_URI: https://auth.zarantonello.dev/api/oidc/userinfo
      OIDC_USERNAME_CLAIM: preferred_username
      PGSSLMODE: disable
      RATE_LIMITER_ENABLED: true
      REDIS_URL: redis://redis:6379
      SMTP_FROM_EMAIL: Outline <outline@zarantonello.dev>
      SMTP_HOST: smtp.purelymail.com
      SMTP_PORT: 465
      URL: https://docs.zarantonello.dev
    image: docker.io/outlinewiki/outline:0.82.0@sha256:494dfb9249a6799ca3d38e2bb1bdf3c9f63632634737bd996ce0b3509fe93499
    labels:
      traefik.enable: true
      traefik.http.routers.outline.entrypoints: cloudflared
      traefik.http.routers.outline.rule: Host(`docs.zarantonello.dev`)
      traefik.http.services.outline.loadbalancer.server.port: 3000
    networks:
      - default
      - traefik_default
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 21127:21127
    volumes:
      - data:/var/lib/outline/data

  # Recurrent job that runs twice a day.
  outline-cron:
    cap_drop:
      - ALL
    depends_on:
      outline:
        condition: service_started
    entrypoint:
      - sh
      - -c
      - while true ; do wget "https://docs.zarantonello.dev/api/cron.daily?token=${UTILS_SECRET}" ; sleep 43200 ; done
    env_file: .env
    image: docker.io/library/alpine:3.21.3@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c
    networks:
      - default
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 22219:22219

  postgres:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      # Configures the user used for healthchecking.
      PGUSER: ${POSTGRES_USER}
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - pg_isready
      timeout: 5s
    image: docker.io/library/postgres:17.3-alpine@sha256:80d3d7d6bb3ddb1e44b79612330f7bfc6c451f093f6dd14a1317e777a260b602
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=70,gid=70
      - /var/run/postgresql:uid=70,gid=70
    # User has to be 70, otherwise the container tries to chown the postgres
    # volume but fails due to insufficient permissions.
    user: 70:70
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    cap_drop:
      - ALL
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 5s
    image: docker.io/library/redis:7.4.2-alpine@sha256:02419de7eddf55aa5bcf49efb74e88fa8d931b4d77c07eff8a6b2144472b6952
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 24056:24056
    volumes:
      - redis:/data

volumes:
  data: {}
  postgres: {}
  redis: {}
