apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: file-server
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: file-server
      apps.zarantonello.dev/namespace: maintenance
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: file-server
        apps.zarantonello.dev/namespace: maintenance
    spec:
      containers:
        - command:
            - caddy
            - file-server
            - --root=/srv
            - --browse
          image: docker.io/library/caddy:2.10.2-alpine@sha256:a4180db0805b3725ddf936d2e6290553745c7339c003565da717ee612fd8a888
          name: file-server
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /srv
              name: data
      enableServiceLinks: false
      volumes:
        - hostPath:
            path: /var/mnt/local-storage
          name: data
