apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: shell
  namespace: maintenance
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: shell
      apps.zarantonello.dev/namespace: maintenance
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: shell
        apps.zarantonello.dev/namespace: maintenance
    spec:
      containers:
        - command:
            - sleep
            - infinity
          image: docker.io/library/alpine:3.22@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1
          name: shell
          volumeMounts:
            - mountPath: /rootfs
              name: rootfs
      enableServiceLinks: false
      hostNetwork: true
      hostPID: true
      nodeSelector:
        maintenance.zarantonello.dev/shell: ""
      volumes:
        - hostPath:
            path: /
          name: rootfs
