apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 10m
  ref:
    branch: main
  url: https://github.com/dvdzara/iac-manifests
