networks:
  alloy_default:
    external: true
  traefik_default:
    external: true

services:
  victorialogs:
    cap_drop:
      - ALL
    command:
      # Logs occupy more space so we store them for a shorter amount of time.
      - -retentionPeriod=30d
    image: docker.io/victoriametrics/victoria-logs:v1.22.2-victorialogs-scratch@sha256:1fce0bf770006b6b0fcc1ad94721f5850af7599994a5cb76ebb1b1af84f9af97
    labels:
      monitoring.collect: true
      monitoring.metrics.port: 9428
      traefik.enable: true
      traefik.http.routers.victorialogs.entrypoints: http
      traefik.http.routers.victorialogs.rule: Host(`victorialogs.zarantonello.net`)
      traefik.http.services.victorialogs.loadbalancer.server.port: 9428
    networks:
      - traefik_default
      - alloy_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 54433:54433
    volumes:
      - $HOME/volumes/victoriametrics/logs:/victoria-logs-data

  victoriametrics:
    cap_drop:
      - ALL
    command:
      # We don't injest many metrics so we can store them for a long time time
      # to be able to do long term analysis.
      - -retentionPeriod=180d
    image: docker.io/victoriametrics/victoria-metrics:v1.117.0-scratch@sha256:0f6c2a4a6a7ea95f98b0078aef206debeb4a7f4ace60a556ba930c557e68df33
    labels:
      monitoring.collect: true
      monitoring.metrics.port: 8428
      traefik.enable: true
      traefik.http.routers.victoriametrics.entrypoints: http
      traefik.http.routers.victoriametrics.rule: Host(`victoriametrics.zarantonello.net`)
      traefik.http.services.victoriametrics.loadbalancer.server.port: 8428
    networks:
      - traefik_default
      - alloy_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 34866:34866
    volumes:
      - $HOME/volumes/victoriametrics/metrics:/victoria-metrics-data
