networks:
  traefik_default:
    external: true
  vmagent_default:
    external: true

services:
  victoriametrics:
    cap_drop:
      - ALL
    command:
      - -retentionPeriod=90d
    image: docker.io/victoriametrics/victoria-metrics:v1.115.0-scratch@sha256:c5edcbd537bb3a8389558c407fceaf0254d071b5fa56b90d811e0a6e63247f05
    labels:
      traefik.enable: true
      traefik.http.routers.victoriametrics.entrypoints: http
      traefik.http.routers.victoriametrics.rule: Host(`victoriametrics.zarantonello.net`)
      traefik.http.services.victoriametrics.loadbalancer.server.port: 8428
      victoriametrics.job: victoriametrics
      victoriametrics.port: 8428
    networks:
      - traefik_default
      - vmagent_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 34866:34866
    volumes:
      - data:/victoria-metrics-data

volumes:
  data: {}
