networks:
  traefik_default:
    external: true
  vmagent_default:
    external: true

services:
  victorialogs:
    cap_drop:
      - ALL
    command:
      # Logs occupy more space so we store them for a shorter amount of time.
      - -retentionPeriod=30d
    image: docker.io/victoriametrics/victoria-logs:v1.17.0-victorialogs-scratch
    labels:
      traefik.enable: true
      traefik.http.routers.victoriametrics.entrypoints: http
      traefik.http.routers.victoriametrics.rule: Host(`victorialogs.zarantonello.net`)
      traefik.http.services.victoriametrics.loadbalancer.server.port: 9428
      victoriametrics.job: victorialogs
      victoriametrics.port: 9428
    networks:
      - traefik_default
      - vmagent_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 54433:54433
    volumes:
      - $HOME/volumes/victoriametrics/logs:/victoria-logs-data

  victoriametrics:
    cap_drop:
      - ALL
    command:
      # We don't injest many metrics so we can store them for a long time time
      # to be able to do long term analysis.
      - -retentionPeriod=180d
    image: docker.io/victoriametrics/victoria-metrics:v1.115.0-scratch@sha256:c5edcbd537bb3a8389558c407fceaf0254d071b5fa56b90d811e0a6e63247f05
    labels:
      traefik.enable: true
      traefik.http.routers.victoriametrics.entrypoints: http
      traefik.http.routers.victoriametrics.rule: Host(`victoriametrics.zarantonello.net`)
      traefik.http.services.victoriametrics.loadbalancer.server.port: 8428
      victoriametrics.job: victoriametrics
      victoriametrics.port: 8428
    networks:
      - traefik_default
      - vmagent_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 34866:34866
    volumes:
      - $HOME/volumes/victoriametrics/metrics:/victoria-metrics-data
