apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: vaultwarden
      apps.zarantonello.dev/namespace: vaultwarden
  # Persistent volume cannot be read by 2 replicas.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: vaultwarden
        apps.zarantonello.dev/namespace: vaultwarden
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: vaultwarden-env
            - secretRef:
                name: vaultwarden-env
          image: quay.io/vaultwarden/server:1.33.2-alpine@sha256:63cce7624f655f83ad5bab66ef62bc3e3327116b068704bfbbda5d0c1b3003be
          name: vaultwarden
          ports:
            - containerPort: 3000
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /data
              name: data
      enableServiceLinks: false
      securityContext:
        fsGroup: 53382
        runAsGroup: 53382
        runAsNonRoot: true
        runAsUser: 53382
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-data
