apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: postgres
      apps.zarantonello.dev/namespace: keycloak
  # Persistent volume cannot be read by 2 replicas.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: postgres
        apps.zarantonello.dev/namespace: keycloak
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: postgres-env
          image: docker.io/library/postgres:17.6-alpine@sha256:3406990b6e4c7192317b6fdc5680498744f6142f01f0287f4ee0420d8c74063c
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: data
              # postgres complains about the lost+found dir.
              subPath: data
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/run/postgresql
              name: sockets
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: srv-0-thi-home
      securityContext:
        fsGroup: 70
        runAsGroup: 70
        runAsNonRoot: true
        runAsUser: 70
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: sockets
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
