machine:
  install:
    disk: /dev/sda
    image: factory.talos.dev/metal-installer/708747e350d604ae9e57227d8dcf274091453ddb1097b765d4ea8884f1992c1f:v1.11.0
  kubelet:
    extraMounts:
      - destination: /var/mnt/longhorn-0
        options:
          - bind
          - rshared
          - rw
        source: /var/mnt/longhorn-0
        type: bind
  network:
    hostname: srv-0-fsk-hetz.servers.zarantonello.dev
    interfaces:
      - addresses:
          - 2a01:4f8:c013:315c::/64
        dhcp: true
        interface: enp1s0
        routes:
          - gateway: fe80::1
            network: ::/0
      - addresses:
          - 10.95.0.1/24
          - fda9:b00c:8b29:33f9::1095:1/120
        interface: wg0
        mtu: 1400
        wireguard:
          listenPort: 51000
          peers:
            # srv-0-cor-home
            - allowedIPs:
                - 10.95.0.2/32
                - fda9:b00c:8b29:33f9::1095:2/128
              endpoint: srv-0-cor-home.servers.zarantonello.dev:51000
              publicKey: dNUWq6FfG7+3AGl5olQOpVel6Ntl4brufEQOlN9VPEM=
            # srv-0-thi-home (no endpoint due to firewall restrictions)
            - allowedIPs:
                - 10.95.0.3/32
                - fda9:b00c:8b29:33f9::1095:3/128
              publicKey: j5Afx7hXJkjHHmDuzmScMrjL3oWpZxT6WL6xMIX87H0=
          privateKey: ENC[AES256_GCM,data:wHZQ4xEqrzZv+n8Tx4LVCu2qlLQdrovALMDPKpmChER+i1exoKRKH+ikzmY=,iv:UfoBTb1yqXuuYvvnIJf0XPI89fMEPfTln1uV6EZ7nYI=,tag:ilasjFY5JNbBNyQXB4Wr2g==,type:str]
  nodeAnnotations:
    # yamllint disable-line rule:quoted-strings
    node.longhorn.io/default-disks-config: '[{ "path": "/var/mnt/longhorn-0", "allowScheduling":true }]'
  nodeLabels:
    node.longhorn.io/create-default-disk: config
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0enMzTWZNVUdGRy9RN2VD
        Snh5TFMrbmNkclBjL3VUdW1oN2x5U1BDdW1RCms2am1GY2RQaytvb3RoZkFYWkZt
        MHlYN2p6ZVh6bFBIVEtlcUNqZ3RhMTgKLS0tIFp2ZWtoaC9NZW1pcFIzNHVqdG5t
        aENCVzdiNmxPdHEvTXlkaWJGamphbGcKueCYjpxNsBA1azvFwFguk4JVlAezuGI0
        xVlgXu3HwPsO+RxUL5iyvxNYfYm9RVohw7Qa+36VnqTgnyBSUdWKXg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10s8xudjc20ujqjsk0asex5vgxqtm3fzrx2g3lzt5lls4rsay6cpqx6rhcc
  encrypted_regex: privateKey
  lastmodified: "2025-09-05T09:31:04Z"
  mac: ENC[AES256_GCM,data:Nn9rTLgUroc/W4k+od4b+syJXfDxDalMEubpI3UjQ4utjIs+lBomkFIzBFQuBX0us5OWr/5wWIYY64sbE/YQNWiiF6PAFzB5MohrXwL6vZMGD9sIa+ciKYIKwJ0sou/lHzyCwQzjuPz5luQSYwjn83fb8opkJ9CguTFXZakTnWE=,iv:C27v1xCVM9T3kX5GWzb/p1muF0R80qbZOukdL+TY/pc=,tag:uv8OxqVQ89LrCnvHEAJDXg==,type:str]
  version: 3.10.2
