certificatesResolvers:
  letsencrypt:
    acme:
      dnsChallenge:
        provider: cloudflare
      storage: /var/lib/traefik/certificates/acme.json
entryPoints:
  cloudflared:
    address: :8081
    forwardedHeaders:
      trustedIPs:
        - 172.16.0.0/12
  http:
    address: :8080
  https:
    address: :8443
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: zarantonello.dev
            sans:
              - "*.zarantonello.dev"
          - main: zarantonello.net
            sans:
              - "*.zarantonello.net"
    http3:
      advertisedPort: 443
  traefik:
    address: :8082
global:
  checkNewVersion: false
  sendAnonymousUsage: true
log:
  format: json
  level: INFO
metrics:
  prometheus:
    headerLabels:
      cfcountry: CF-IPCountry
      useragent: User-Agent
ping: {}
providers:
  docker:
    exposedByDefault: false
    network: traefik_default
