apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/ips: 100.64.0.1
    lbipam.cilium.io/sharing-cross-namespace: "*"
    lbipam.cilium.io/sharing-key: hetz-0-tailscale
  name: mail-internal
spec:
  ports:
    - name: smtps
      port: 465
      targetPort: smtps
    - name: imaps
      port: 993
      targetPort: imaps
  selector:
    apps.zarantonello.dev/name: stalwart
    apps.zarantonello.dev/namespace: stalwart
  type: LoadBalancer
