services:
  server:
    cap_drop:
      - ALL
    entrypoint:
      - java
      - -jar
      - server.jar
    image: docker.io/library/eclipse-temurin:24-jre-alpine
    ports:
      - 25565:25565
    labels:
      monitoring.collect: true
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=42428,gid=42428
    user: 42428:42428
    volumes:
      - $HOME/volumes/minecraft:/srv
    working_dir: /srv
