services:
  server:
    cap_drop:
      - ALL
    # Download the fabric launcher jar from https://fabricmc.net/use/server and
    # copy the file into the root folder of the minecraft volume as fabric.jar.
    entrypoint:
      - java
      - -jar
      - fabric.jar
    image: docker.io/library/eclipse-temurin:24-jre-alpine@sha256:6454f0a4794a77f156c6fb9248803d573ea2395afe67ec2ec42c1c16f31e0cdf
    labels:
      monitoring.collect: true
    ports:
      - "[fd7a:115c:a1e0::d901:7769]:25565:25565"
      - 100.117.119.101:25565:25565
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=42428,gid=42428
    user: 42428:42428
    volumes:
      - $HOME/volumes/minecraft:/srv
    working_dir: /srv
