creation_rules:
  # Generate a secret key with age-keygen -o /workspace/age-secret-key.txt and
  # replace the key below with your public key.
  - age: age10s8xudjc20ujqjsk0asex5vgxqtm3fzrx2g3lzt5lls4rsay6cpqx6rhcc
    path_regex: kubernetes/.+/generated/secrets/.+
  - age: age10s8xudjc20ujqjsk0asex5vgxqtm3fzrx2g3lzt5lls4rsay6cpqx6rhcc
    encrypted_regex: ^(data|stringData)$
    path_regex: kubernetes/.+/secrets/.+\.yaml

stores:
  yaml:
    indent: 2
