apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    apps.zarantonello.dev/name: mimir
    apps.zarantonello.dev/namespace: mimir
