# SETUP:
#
# Create a .env file with:
#
# - WOODPECKER_AGENT_SECRET
# - WOODPECKER_GITHUB_CLIENT
# - WOODPECKER_GITHUB_SECRET

networks:
  cloudflared_default:
    external: true

services:
  # kics-scan ignore-block
  chown-volumes:
    entrypoint:
      - sh
      - -c
      - chown -R 4518:4518 /volumes/data
    image: docker.io/library/busybox:1.37.0-musl@sha256:37ccc05112d0a7162b605c375f5c0f5cfbc6e6c4fc8030ead6ae26a18c28a542
    read_only: true
    restart: "no"
    security_opt:
      - no-new-privileges:true
    user: 0:0
    volumes:
      - data:/volumes/data

  woodpecker-server:
    cap_drop:
      - ALL
    depends_on:
      chown-volumes:
        condition: service_completed_successfully
    env_file: .env
    environment:
      - WOODPECKER_ADMIN=dvdzara
      - WOODPECKER_HOST=https://ci.zarantonello.dev
      - WOODPECKER_GITHUB=true
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - woodpecker-server
        - ping
      timeout: 5s
    image: docker.io/woodpeckerci/woodpecker-server:v3.0.1@sha256:6e54508d3b2373a2c5beb2c3384d7c79a5fd957c5509295bfdf975e8f3292101
    networks:
      cloudflared_default:
        aliases:
          - woodpecker
    ports:
      - 100.106.32.89:9000:9000
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 4518:4518
    volumes:
      - data:/var/lib/woodpecker

volumes:
  data: {}
