configs:
  vmagent-scrape:
    file: ./scrape.yml

networks:
  vmagent_default:
    name: vmagent_default

services:
  vmagent:
    cap_drop:
      - ALL
    command:
      - -promscrape.config=/etc/victoriametrics/scrape.yml
      - -remoteWrite.url=http://victoriametrics.zarantonello.net/api/v1/write
      - -remoteWrite.label=host=${HOSTNAME}
    configs:
      - source: vmagent-scrape
        target: /etc/victoriametrics/scrape.yml
    extra_hosts:
      - hosts.docker.internal:host-gateway
    group_add:
      - "993"
    image: docker.io/victoriametrics/vmagent:v1.109.0-scratch@sha256:a37122d646eda9e56d986fa49f3490429f8373c343f599098a30be9c05297788
    labels:
      victoriametrics.job: vmagent
      victoriametrics.port: 8429
    networks:
      - vmagent_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 14677:14677
    volumes:
      - data:/vmagent-remotewrite-data
      - /var/run/docker.sock:/var/run/docker.sock:z

volumes:
  data: {}
