apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
spec:
  selector:
    matchLabels:
      zarantonello.dev/app: alloy
      zarantonello.dev/namespace: alloy
  template:
    metadata:
      labels:
        monitoring.zarantonello.dev/job: alloy
        monitoring.zarantonello.dev/port: "12345"
        zarantonello.dev/app: alloy
        zarantonello.dev/namespace: alloy
    spec:
      containers:
        - args:
            - run
            - --server.http.listen-addr=[::]:12345
            - --storage.path=/var/lib/alloy/data
            - /etc/alloy/alloy.alloy
          env:
            # Let alloy know what is the hostname of the node its running on.
            - name: NODE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: docker.io/grafana/alloy:v1.6.1
          name: alloy
          ports:
            - containerPort: 12345
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/alloy/alloy.alloy
              name: alloy-config
              subPath: alloy.alloy
            - mountPath: /var/lib/alloy
              name: alloy-data
      enableServiceLinks: false
      securityContext:
        fsGroup: 38082
        runAsGroup: 38082
        runAsNonRoot: true
        runAsUser: 38082
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: alloy
      volumes:
        - configMap:
            name: alloy
          name: alloy-config
        # Just need to persist stuff until it is sent to loki or
        # victoriametrics. It's not important if we lose some minutes worth
        # of data.
        - emptyDir: {}
          name: alloy-data
