# SETUP:
#
# Create a .env file with
#
# - MINIO_IDENTITY_OPENID_CLIENT_ID
# - MINIO_IDENTITY_OPENID_CLIENT_SECRET
# - MINIO_ROOT_PASSWORD
# - MINIO_ROOT_USER
#
# TIP: In the host's /etc/fstab file mount the 4 data disks with the nofail
# option to make the system boot even if one the data drives fails.

networks:
  traefik_default:
    external: true

services:
  minio:
    cap_drop:
      - ALL
    command:
      - server
    env_file: .env
    environment:
      MINIO_API_ROOT_ACCESS: off
      MINIO_BROWSER_REDIRECT: false
      MINIO_COMPRESSION_ENABLE: on
      MINIO_CONSOLE_ADDRESS: :9001
      MINIO_IDENTITY_OPENID_CLAIM_NAME: minio-policy
      MINIO_IDENTITY_OPENID_CONFIG_URL: https://auth.zarantonello.dev/realms/homelab/.well-known/openid-configuration
      MINIO_IDENTITY_OPENID_DISPLAY_NAME: Keycloak
      MINIO_IDENTITY_OPENID_SCOPES: email,profile,openid
    # Host specific configuration for volumes, image and http host.
    extends:
      file: ./${HOSTNAME}.docker-compose.yml
      service: minio
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - curl
        - http://localhost:9000/minio/health/live
      timeout: 5s
    labels:
      traefik.enable: true
      traefik.http.routers.minio-dashboard.entrypoints: https
      traefik.http.routers.minio-dashboard.service: minio-dashboard
      traefik.http.services.minio-dashboard.loadbalancer.server.port: 9001
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 29349:29349
