services:
  minio:
    environment:
      MINIO_BROWSER_REDIRECT_URL: https://minio-prem-0.zarantonello.dev
      MINIO_DOMAIN: s3-prem-0.zarantonello.dev
      MINIO_VOLUMES: /data
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z@sha256:a1ea29fa28355559ef137d71fc570e508a214ec84ff8083e39bc5428980b015e
    labels:
      traefik.http.routers.minio-dashboard.rule: Host(`minio-prem-0.zarantonello.dev`)
      traefik.http.routers.minio-s3.rule: Host(`s3-prem-0.zarantonello.dev`)
    volumes:
      - $HOME/volumes/minio:/data
