services:
  minio:
    environment:
      MINIO_BROWSER_REDIRECT_URL: https://minio-0.zarantonello.dev
      MINIO_DOMAIN: s3.zarantonello.dev
      MINIO_VOLUMES: /data
    image: quay.io/minio/minio:RELEASE.2025-04-03T14-56-28Z@sha256:a640662d97632f7b94e9dee8cbb7da5c20db24879725cb4fac36f1e220cd528a
    labels:
      traefik.http.routers.minio-dashboard.rule: Host(`minio-0.zarantonello.dev`)
      traefik.http.routers.minio-s3.entrypoints: https,cloudflared
      traefik.http.routers.minio-s3.rule: Host(`s3.zarantonello.dev`)
      traefik.http.routers.minio-s3.service: minio-s3
      traefik.http.services.minio-s3.loadbalancer.server.port: 9000
    volumes:
      - $HOME/volumes/minio-data:/data
