# SETUP:
#
# Create a .env file with:
#
# - WOODPECKER_AGENT_SECRET

services:
  woodpecker-agent:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      WOODPECKER_SERVER: 100.106.32.89:9000
    # Add to docker group to use the docker socket.
    group_add:
      - "992"
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - woodpecker-agent
        - ping
      timeout: 5s
    image: docker.io/woodpeckerci/woodpecker-agent:v3.1.0@sha256:95550c457918ce6b6c32a72918d7c7d4b39ef268d38a5da63b5ffb1bb1ee35f0
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 36307:36307
    volumes:
      # kics-scan ignore-line
      - /var/run/docker.sock:/var/run/docker.sock:z
