cluster:
  # I don't have resources to run dedicated control plane nodes.
  allowSchedulingOnControlPlanes: true
  apiServer:
    admissionControl:
      - configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1alpha1
          defaults:
            audit: restricted
            audit-version: latest
            enforce: restricted
            enforce-version: latest
            warn: restricted
            warn-version: latest
          exemptions:
            # kube-system is added automatically.
            namespaces: []
          kind: PodSecurityConfiguration
        name: PodSecurity
    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
        - level: None
    # The default SAN for the endpoint will be added by `talosctl gen config`.
    # These additional ones are used to connect to the API server via tailscale.
    certSANs:
      - 100.111.94.27
  controllerManager:
    extraArgs:
      node-cidr-mask-size-ipv4: "24"
      node-cidr-mask-size-ipv6: "120"
  # CoreDNS is deployed manually.
  coreDNS:
    disabled: true
  discovery:
    enabled: true
  network:
    # Disable Flannel (the default CNI) to use Cilium.
    cni:
      name: none
    dnsDomain: k8s.zarantonello.dev
    podSubnets:
      - 10.96.0.0/16
      - fda9:b00c:8b29:33f9::1096:0/112
    serviceSubnets:
      - 10.97.0.0/16
      - fda9:b00c:8b29:33f9::1097:0/112
  # Disable kube-proxy as its provided by Cilium.
  proxy:
    disabled: true
debug: false
machine:
  features:
    apidCheckExtKeyUsage: true
    diskQuotaSupport: false
    hostDNS:
      enabled: false
    kubePrism:
      enabled: false
    rbac: true
    stableHostname: true
  kubelet:
    # Points to the CoreDNS service.
    clusterDNS:
      - 10.97.0.10
    extraConfig:
      nodeStatusUpdateFrequency: 1m
    nodeIP:
      validSubnets:
        - 10.95.0.0/24
        - fda9:b00c:8b29:33f9::1095:0/120
persist: true
version: v1alpha1
