apiVersion: v1alpha1
# All variables below will be encrypted by sops, these are the clear values for
# the non secret ones.
# - TS_ENABLE_METRICS=true
# Also remember to set TS_AUTHKEY.
environment:
  - ENC[AES256_GCM,data:hcUbVSHN9q/J/OQp5CPLvG0C/r0fYA==,iv:7tOeuM9sgJDXkL1V68TlDL4GGYiFE4m2NwHUQNHziDg=,tag:2xUCLgezbBEr3GACALda9A==,type:str]
  - ENC[AES256_GCM,data:6YzEhnqHaCrLQyChjm6z9aHS5eILkbMPEKG0/2EpXMPCNlwp5nXmPj9uRRY8v2aWhy5bDzELvQIXkEnML+hc0Ne8jI0kQwEC,iv:20ygx00V6fOGFfRz5DX8SEnQrHrIuIwZkRW3RidylH0=,tag:ngEKDP4d2sngRXticdvi/w==,type:str]
kind: ExtensionServiceConfig
name: tailscale
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VXBvVDA3K3VxL0xiVmhz
        Sk1KWUdtdHdjSG9uRUx3WUZmR0dYelVpTUVNCm1YSlJoMzdyVjhLaXJBTk9nanIz
        RnlyaXhCTEdGSzJZSkVqWlFmTjhQYmMKLS0tIEpZQk1vcDBUZWFwU3Uxdnh1eHZo
        NmxqUG1CQmJrWmMrOFZuMVRFWWs1am8Ke/g2lfKApXoGjk9SCSc4BGQ+WtKuA+G8
        QXDpV3WjXprsiXr1NxPuRE8slhTS0fMfqKb1KeC1fO+iHFy/ZOjR3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10s8xudjc20ujqjsk0asex5vgxqtm3fzrx2g3lzt5lls4rsay6cpqx6rhcc
  azure_kv: []
  encrypted_regex: environment
  gcp_kms: []
  hc_vault: []
  kms: []
  lastmodified: "2025-08-31T19:24:33Z"
  mac: ENC[AES256_GCM,data:EOFkxYmITmyRjQGzU3LHlEG8JVN+ayAA95eclYDhZ2xSLlfDNiZa8De9gxgjcifAm6iBW/QXs50FTXSByLS6yOUt8cITXD9AFjlVqUEl2Aaq/7kiN7qoMtObeZrD+N/DQ8QqsNK+ku2SHNONjCoJQzr4BLTz8Mu04Y66yHUHJlg=,iv:xThi94rPMBeLDrBbbJs9pU05Jt892cm+Mn/3e/k4j20=,tag:Giiz0v2Iao37ssCsUbbt2g==,type:str]
  pgp: []
  version: 3.9.4
