# SETUP:
#
# To use authelia's authentication, you must run the command:
#
# /filebrowser config set --auth.method=proxy --auth.header=Remote-User

networks:
  traefik_default:
    external: true

services:
  filebrowser:
    cap_drop:
      - ALL
    environment:
      FB_BASE_URL: https://files.zarantonello.dev
      FB_DATABASE: /var/lib/filebrowser/database/db.sqlite
      FB_PORT: 3000
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - /healthcheck.sh
      timeout: 5s
    image: docker.io/filebrowser/filebrowser:v2.32.0@sha256:593478e3c24c5ea9f5d7478dc549965b7bc7030707291006ce8d0b6162d3454b
    labels:
      traefik.enable: true
      traefik.http.routers.filebrowser.middlewares: autheliaForwardAuth@file
      traefik.http.routers.filebrowser.rule: Host(`files.zarantonello.dev`)
      traefik.http.services.filebrowser.loadbalancer.server.port: 3000
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 50788:50788
    volumes:
      - data:/srv
      - database:/var/lib/filebrowser/database

volumes:
  data: {}
  database: {}
