# Example /etc/fstab with 4 disks:
#
# ## garage 0 ##
#
# # sda
# UUID=your-fs-uuid /home/user/volumes/garage/0/data/sda btrfs subvol=@data,nofail 0 0
#
# # sdb
# UUID=your-fs-uuid /home/user/volumes/garage/0/data/sdb btrfs subvol=@data,nofail 0 0
# UUID=your-fs-uuid /home/user/volumes/garage/0/metadata btrfs subvol=@metadata,nofail 0 0
#
# ## garage 1 ##
#
# # sdc
# UUID=your-fs-uuid /home/user/volumes/garage/1/data/sdc btrfs subvol=@data,nofail 0 0
# UUID=your-fs-uuid /home/user/volumes/garage/1/metadata btrfs subvol=@metadata,nofail 0 0
#
# # sdd
# UUID=your-fs-uuid /home/user/volumes/garage/1/data/sdd btrfs subvol=@data,nofail 0 0
#
# ## garage snapshots ##
#
# # sda
# UUID=your-fs-uuid /home/user/volumes/garage/0/snapshots btrfs subvol=@snapshots,nofail 0 0
#
# # sdd
# UUID=your-fs-uuid /home/user/volumes/garage/1/snapshots btrfs subvol=@snapshots,nofail 0 0

configs:
  garage-0:
    file: ./garage-0.toml
  garage-1:
    file: ./garage-1.toml

name: garage

networks:
  alloy_default:
    external: true
  traefik_default:
    external: true

services:
  garage-0:
    configs:
      - source: garage-0
        target: /etc/garage.toml
    extends:
      file: ../docker-compose.base.yml
      service: garage
    labels:
      traefik.http.routers.garage-s3-0.entrypoints: http,https,cloudflared
      traefik.http.routers.garage-s3-0.rule: Host(`s3-prem-2.zarantonello.dev`)
      traefik.http.routers.garage-s3-0.service: garage-s3-0
      traefik.http.services.garage-s3-0.loadbalancer.server.port: 3900
    volumes:
      - $HOME/volumes/garage/0:/var/lib/garage

  garage-1:
    configs:
      - source: garage-1
        target: /etc/garage.toml
    extends:
      file: ../docker-compose.base.yml
      service: garage
    labels:
      traefik.http.routers.garage-s3-1.entrypoints: http,https,cloudflared
      traefik.http.routers.garage-s3-1.rule: Host(`s3-prem-2.zarantonello.dev`)
      traefik.http.routers.garage-s3-1.service: garage-s3-1
      traefik.http.services.garage-s3-1.loadbalancer.server.port: 3900
    volumes:
      - $HOME/volumes/garage/1:/var/lib/garage
