db_engine = "lmdb"

block_size = "50M"
compression_level = 10

metadata_dir = "/var/lib/garage/metadata"
metadata_snapshots_dir = "/var/lib/garage/snapshots"
metadata_auto_snapshot_interval = "6h"

data_dir = [
  { path = "/var/lib/garage/data/sdc", capacity = "500g" },
  { path = "/var/lib/garage/data/sdd", capacity = "500g" },
]

replication_factor = 2
consistency_mode = "consistent"

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "garage-1:3901"

[s3_api]
s3_region = "default"
api_bind_addr = "[::]:3900"

[admin]
api_bind_addr = "[::]:3903"
