apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: postgres
      apps.zarantonello.dev/namespace: outline
  # Persistent volume cannot be read by 2 replicas.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: postgres
        apps.zarantonello.dev/namespace: outline
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: postgres-env
          # TODO: I use 18 because of changes with PGDATA (solves some volume
          # problems), need to set minor version when released.
          image: docker.io/library/postgres:18beta3@sha256:9e64903e2ad74c67ece96d917344593b96dfa54af61e0c300bf2ac33c74dd091
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: data
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/run/postgresql
              name: sockets
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: srv-0-thi-home
      securityContext:
        fsGroup: 70
        runAsGroup: 70
        runAsNonRoot: true
        runAsUser: 70
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: sockets
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
