apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: postgres
      apps.zarantonello.dev/namespace: outline
  # Persistent volume cannot be read by 2 replicas.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: postgres
        apps.zarantonello.dev/namespace: outline
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: postgres-env
          image: docker.io/library/postgres:17.4-alpine@sha256:7062a2109c4b51f3c792c7ea01e83ed12ef9a980886e3b3d380a7d2e5f6ce3f5
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/run/postgresql
              name: tmp-sockets
      enableServiceLinks: false
      securityContext:
        fsGroup: 70
        runAsGroup: 70
        runAsNonRoot: true
        runAsUser: 70
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: tmp-sockets
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
