apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: blocky
      apps.zarantonello.dev/namespace: blocky
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: blocky
        apps.zarantonello.dev/namespace: blocky
        monitoring.zarantonello.dev/job: blocky
        monitoring.zarantonello.dev/port: "8080"
    spec:
      containers:
        - image: ghcr.io/0xerr0r/blocky:0.24@sha256:9a82e0235c52ef3048586f8006add06e52132adaae70d02f980569dae16421a2
          name: blocky
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 8080
              name: http
          readinessProbe:
            exec:
              command:
                - /app/blocky
                - healthcheck
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /app/config.yml
              name: blocky-config
              subPath: blocky.yaml
      securityContext:
        runAsGroup: 21575
        runAsNonRoot: true
        runAsUser: 21575
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - configMap:
            name: blocky
          name: blocky-config
