# SETUP:
#
# Create a .env file with:
#
# - WOODPECKER_AGENT_SECRET

services:
  woodpecker-agent:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      WOODPECKER_SERVER: 100.106.32.89:9000
    # Add to docker group to use the docker socket.
    group_add:
      - "993"
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - woodpecker-agent
        - ping
      timeout: 5s
    image: docker.io/woodpeckerci/woodpecker-agent:v2.7.3@sha256:a50d7d45b071ad66ad6ebe17b21ac42a9ec79ac72ae5a9acf611d95ac37340a3
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 36307:36307
    volumes:
      # kics-scan ignore-line
      - /var/run/docker.sock:/var/run/docker.sock:z
