blocking:
  blockType: nxDomain
  clientGroupsBlock:
    default:
      - default
  denylists:
    default:
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/dyndns.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/fake-onlydomains.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/hoster-onlydomains.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.samsung.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.tiktok.extended.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.winoffice.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.xiaomi.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.plus.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt
  loading:
    concurrency: 2
    downloads:
      cooldown: 10s
      timeout: 60s
    refreshPeriod: 72h
bootstrapDns:
  - tcp+udp:1.1.1.1
caching:
  prefetching: true
customDNS:
  # yamllint disable rule:key-ordering
  mapping:
    # websites
    grafana.zarantonello.net: 100.106.32.89,fd7a:115c:a1e0::f401:f415
    minio-0.zarantonello.net: 100.106.32.89,fd7a:115c:a1e0::f401:f415
    minio-1.zarantonello.dev: 100.81.212.20,fd7a:115c:a1e0::7301:d415
    photos.zarantonello.net: 100.106.32.89,fd7a:115c:a1e0::f401:f415
    vault.zarantonello.net: 100.106.32.89,fd7a:115c:a1e0::f401:f415
    # servers
    hp2420.srv.zarantonello.dev: 100.81.212.20,fd7a:115c:a1e0::7301:d415
    x555sj.srv.zarantonello.dev: 100.106.32.89,fd7a:115c:a1e0::f401:f415
  # yamllint enable rule:key-ordering
fqdnOnly:
  enable: true
ports:
  dns: 53
  http: 8080
prometheus:
  enable: true
queryLog:
  type: none
upstreams:
  groups:
    default:
      - tcp-tls:one.one.one.one:853
  strategy: random
