apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
  - files:
      - generated/configs/zot.yaml
    name: zot-config
kind: Kustomization
namespace: zot
resources:
  - deployments/zot.yaml
  - namespace.yaml
  - service-accounts/default.yaml
  - services/http.yaml
