# kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8

networks:
  caddy_default:
    external: true
  default: {}

services:
  # kics-scan ignore-block
  chown-volumes:
    entrypoint:
      - sh
      - -c
      - chown -R 28361:28361 /volumes/data && chown -R 26418:26418 /volumes/redis
    image: docker.io/library/busybox:1.37.0-musl@sha256:e95352f7c5174c96ffc684150c9d08fc3ba26ac2f37c613c398fd369e15a0789
    read_only: true
    restart: "no"
    security_opt:
      - no-new-privileges:true
    user: 0:0
    volumes:
      - data:/volumes/data
      - redis:/volumes/redis

  redis:
    cap_drop:
      - ALL
    depends_on:
      chown-volumes:
        condition: service_completed_successfully
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 5s
    image: docker.io/library/redis:7.4.1-alpine@sha256:de13e74e14b98eb96bdf886791ae47686c3c5d29f9d5f85ea55206843e3fce26
    networks:
      - default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 26418:26418
    volumes:
      - redis:/data

  registry:
    cap_drop:
      - ALL
    depends_on:
      chown-volumes:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    environment:
      REGISTRY_HTTP_HOST: https://registry.zarantonello.dev
      REGISTRY_REDIS_ADDR: redis:6379
      REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: redis
      REGISTRY_STORAGE_DELETE_ENABLED: true
    image: docker.io/library/registry:2.8.3@sha256:ac0192b549007e22998eb74e8d8488dcfe70f1489520c3b144a6047ac5efbe90
    networks:
      caddy_default:
        aliases:
          - registry
      default: {}
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 28361:28361
    volumes:
      - data:/var/lib/registry

  registry_garbage_collect:
    depends_on:
      registry:
        condition: service_started
    entrypoint:
      - sh
      - -c
      - while true ; do registry garbage-collect -m /etc/docker/registry/config.yml && sleep 600 ; done
    extends:
      service: registry
    networks:
      - default

  # kics-scan ignore-block
  ui:
    environment:
      DELETE_IMAGES: true
      NGINX_PROXY_PASS_URL: http://registry:5000
      PULL_URL: registry.zarantonello.dev
      SINGLE_REGISTRY: true
    image: docker.io/joxit/docker-registry-ui:2.5.7@sha256:5594b76bf8dd9de479648e28f38572d020d260568be40b7e52b9758b442275e1
    networks:
      caddy_default:
        aliases:
          - registry_ui
      default: {}
    restart: always
    security_opt:
      - no-new-privileges:true

volumes:
  data: {}
  redis: {}
