# SETUP:
#
# Create a .env file with:
#
# - ADMIN_TOKEN
# - PUSH_INSTALLATION_ID
# - PUSH_INSTALLATION_KEY
# - SMTP_PASSWORD
# - SMTP_USERNAME

networks:
  traefik_default:
    external: true

services:
  vaultwarden:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      DOMAIN: https://vault.zarantonello.net
      INVITATIONS_ALLOWED: false
      PASSWORD_HINTS_ALLOWED: false
      PUSH_ENABLED: true
      PUSH_IDENTITY_URI: https://identity.bitwarden.eu
      PUSH_RELAY_URI: https://api.bitwarden.eu
      ROCKET_PORT: 3000
      SENDS_ALLOWED: false
      SIGNUPS_ALLOWED: false
      SMTP_FROM: vault@zarantonello.net
      SMTP_HOST: smtp.purelymail.com
      SMTP_PORT: 465
      SMTP_SECURITY: force_tls
      TRASH_AUTO_DELETE_DAYS: 60
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - /healthcheck.sh
      timeout: 5s
    image: quay.io/vaultwarden/server:1.32.6-alpine@sha256:dd42e79b200bec6bca1d34e9c51f3fbd263b21fdf8651619b59b728aaa1c4386
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.rule: Host(`vault.zarantonello.net`)
      traefik.http.services.vaultwarden.loadbalancer.server.port: 3000
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 53382:53382
    volumes:
      - data:/data

volumes:
  data: {}
