# SETUP:
#
# Create a .env file with:
#
# - ADMIN_TOKEN
# - PUSH_INSTALLATION_ID
# - PUSH_INSTALLATION_KEY
# - SMTP_PASSWORD
# - SMTP_USERNAME

networks:
  caddy_default:
    external: true

services:
  # kics-scan ignore-block
  chown-volumes:
    entrypoint:
      - sh
      - -c
      - chown -R 53382:53382 /volumes/data
    image: docker.io/library/busybox:1.37.0-musl@sha256:e95352f7c5174c96ffc684150c9d08fc3ba26ac2f37c613c398fd369e15a0789
    read_only: true
    restart: "no"
    security_opt:
      - no-new-privileges:true
    user: 0:0
    volumes:
      - data:/volumes/data

  vaultwarden:
    cap_drop:
      - ALL
    depends_on:
      chown-volumes:
        condition: service_completed_successfully
    env_file: .env
    environment:
      DOMAIN: https://vault.zarantonello.net
      INVITATIONS_ALLOWED: false
      PASSWORD_HINTS_ALLOWED: false
      PUSH_ENABLED: true
      PUSH_IDENTITY_URI: https://identity.bitwarden.eu
      PUSH_RELAY_URI: https://api.bitwarden.eu
      ROCKET_PORT: 3000
      SENDS_ALLOWED: false
      SIGNUPS_ALLOWED: false
      SMTP_FROM: vault@zarantonello.net
      SMTP_HOST: smtp.purelymail.com
      SMTP_PORT: 465
      SMTP_SECURITY: force_tls
      TRASH_AUTO_DELETE_DAYS: 60
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - /healthcheck.sh
      timeout: 5s
    image: quay.io/vaultwarden/server:1.32.5-alpine@sha256:76d46d32ba4120b022e0a69487f9fd79fc52e2765b1650c5c51a5dd912a3c288
    networks:
      caddy_default:
        aliases:
          - vaultwarden
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 53382:53382
    volumes:
      - data:/data

volumes:
  data: {}
