services:
  node-exporter:
    cap_drop:
      - ALL
    command:
      - --path.rootfs=/host
    image: quay.io/prometheus/node-exporter:v1.8.2@sha256:4032c6d5bfd752342c3e631c2f1de93ba6b86c41db6b167b9a35372c139e7706
    labels:
      victoriametrics.job: node-exporter
      victoriametrics.port: 9100
    network_mode: host
    pid: host
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 3095:3095
    volumes:
      - /:/host:ro,rslave
