apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      version: 1.17.1
  install:
    crds: Create
  interval: 5m
  releaseName: cert-manager
  upgrade:
    crds: Create
  values:
    crds:
      enabled: true
