apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: node-exporter
      apps.zarantonello.dev/namespace: node-exporter
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: node-exporter
        apps.zarantonello.dev/namespace: node-exporter
        monitoring.zarantonello.dev/job: node-exporter
        monitoring.zarantonello.dev/port: "9100"
    spec:
      containers:
        - args:
            - --path.rootfs=/host
          image: quay.io/prometheus/node-exporter:v1.9.0@sha256:c99d7ee4d12a38661788f60d9eca493f08584e2e544bbd3b3fca64749f86b848
          name: node-exporter
          ports:
            - containerPort: 9100
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /host
              name: host-fs
      enableServiceLinks: false
      hostNetwork: true
      hostPID: true
      securityContext:
        fsGroup: 7587
        runAsGroup: 7587
        runAsNonRoot: true
        runAsUser: 7587
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - hostPath:
            path: /
          name: host-fs
