# SETUP:
#
# Create .env file with:
#
# - CF_DNS_API_TOKEN
# - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL

configs:
  traefik:
    file: ./traefik.yml

services:
  # kics-scan ignore-block
  chown-volumes:
    entrypoint:
      - sh
      - -c
      - chown -R 51664:51664 /var/lib/volumes/certificates
    image: docker.io/library/busybox:1.37.0-musl@sha256:e95352f7c5174c96ffc684150c9d08fc3ba26ac2f37c613c398fd369e15a0789
    network_mode: none
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - certificates:/var/lib/volumes/certificates

  traefik:
    cap_drop:
      - ALL
    configs:
      - source: traefik
        target: /etc/traefik/traefik.yml
    depends_on:
      chown-volumes:
        condition: service_completed_successfully
    env_file: .env
    group_add:
      - "993"
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - traefik
        - healthcheck
      timeout: 5s
    image: docker.io/library/traefik:v3.2.1@sha256:1a3e33f976d10f45efd613aa64814867068bf51c782599a70ef370447686291b
    networks:
      default:
        aliases:
          - traefik
    # kics-scan ignore-block
    ports:
      - 443:1443/tcp
      - 443:1443/udp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 51664:51664
    volumes:
      - certificates:/var/lib/traefik/certificates
      # kics-scan ignore-line
      - /var/run/docker.sock:/var/run/docker.sock:z

volumes:
  certificates: {}
