# SETUP:
#
# Create .env file with:
#
# - CF_DNS_API_TOKEN
# - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL

configs:
  traefik:
    file: ./traefik.yml
  traefik-middlewares:
    file: ./middlewares.yml

networks:
  traefik_default:
    name: traefik_default
  vmagent_default:
    external: true

services:
  traefik:
    cap_drop:
      - ALL
    configs:
      - source: traefik
        target: /etc/traefik/traefik.yml
      - source: traefik-middlewares
        target: /etc/traefik/middlewares.yml
    env_file: .env
    group_add:
      - "993"
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - traefik
        - healthcheck
      timeout: 5s
    image: docker.io/library/traefik:v3.3.1@sha256:a0a80d2e1604d62218e58fd21095d64b55a38445eda7bf235687cafca7d21eaf
    labels:
      victoriametrics.job: traefik
      victoriametrics.port: 8000
    networks:
      traefik_default:
        aliases:
          - traefik
      vmagent_default: {}
    ports:
      - 80:8080
      - 443:8443/tcp
      - 443:8443/udp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 51664:51664
    volumes:
      - certificates:/var/lib/traefik/certificates
      - /var/run/docker.sock:/var/run/docker.sock:z

volumes:
  certificates: {}
