certificatesResolvers:
  letsencrypt:
    acme:
      dnsChallenge:
        provider: cloudflare
      storage: /var/lib/traefik/certificates/acme.json
entryPoints:
  http:
    address: :8080
  https:
    address: :8443
    asDefault: true
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: zarantonello.dev
            sans:
              - "*.zarantonello.dev"
          - main: zarantonello.net
            sans:
              - "*.zarantonello.net"
    http3:
      advertisedPort: 443
  traefik:
    address: :8000
global:
  checkNewVersion: false
  sendAnonymousUsage: true
log:
  format: json
  level: INFO
metrics:
  prometheus:
    headerLabels:
      cfcountry: CF-IPCountry
      useragent: User-Agent
ping: {}
providers:
  docker:
    exposedByDefault: false
    network: traefik_default
