apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: kustomize-controller
      apps.zarantonello.dev/namespace: fluxcd
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: kustomize-controller
        apps.zarantonello.dev/namespace: fluxcd
        monitoring.zarantonello.dev/job: kustomize-controller
        monitoring.zarantonello.dev/port: "8080"
    spec:
      containers:
        - args:
            - --enable-leader-election
          image: ghcr.io/fluxcd/kustomize-controller:v1.5.1@sha256:b89935f9428764c389c5192fdb8f6c53b66e365fa09ac8cec597e82273e9f518
          name: kustomize-controller
          ports:
            - containerPort: 8080
              name: http-metrics
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      enableServiceLinks: false
      securityContext:
        fsGroup: 28700
        runAsGroup: 28700
        runAsNonRoot: true
        runAsUser: 28700
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: kustomize-controller
      volumes:
        - emptyDir: {}
          name: tmp
