# Create a .env file with:
#
# WOODPECKER_GITHUB_CLIENT=
# WOODPECKER_GITHUB_SECRET=
# WOODPECKER_AGENT_SECRET=

name: woodpecker-server

networks:
  cloudflared:
    external: true

services:
  woodpecker-server:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      - WOODPECKER_ADMIN=dvdzara
      - WOODPECKER_HOST=https://ci.zarantonello.dev
      - WOODPECKER_GITHUB=true
    image: docker.io/woodpeckerci/woodpecker-server:v2.7.1-alpine
    networks:
      cloudflared:
        aliases:
          - woodpecker
    ports:
      - 100.106.32.89:9000:9000
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 4518:4518
    volumes:
      - data:/var/lib/woodpecker

volumes:
  data: {}
