# Create a .env file with:
#
# WOODPECKER_GITHUB_CLIENT=
# WOODPECKER_GITHUB_SECRET=
# WOODPECKER_AGENT_SECRET=

name: woodpecker-server

services:
  woodpecker-server:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      - WOODPECKER_ADMIN=dvdzara
      - WOODPECKER_HOST=https://ci.zarantonello.dev
      - WOODPECKER_GITHUB=true
    image: docker.io/woodpeckerci/woodpecker-server:v2.7.1-alpine
    ports:
      - 3003:8000
      - 3004:9000
    read_only: true
    restart: always
    user: 4518:4518
    volumes:
      - data:/var/lib/woodpecker

volumes:
  data: {}
