# SETUP:
#
# Create a .env file with:
#
# - WOODPECKER_AGENT_SECRET
# - WOODPECKER_GITHUB_CLIENT
# - WOODPECKER_GITHUB_SECRET

networks:
  cloudflared_default:
    external: true

services:
  woodpecker-server:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      - WOODPECKER_ADMIN=dvdzara
      - WOODPECKER_HOST=https://ci.zarantonello.dev
      - WOODPECKER_GITHUB=true
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - woodpecker-server
        - ping
      timeout: 5s
    image: docker.io/woodpeckerci/woodpecker-server:v2.7.3@sha256:d98e9ede28e1feccc412a595ad46876a74284dadc99eed5a330c01da2f4576a7
    networks:
      cloudflared_default:
        aliases:
          - woodpecker
    ports:
      - 100.106.32.89:9000:9000
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 4518:4518
    volumes:
      - data:/var/lib/woodpecker

volumes:
  data: {}
