apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: default
spec:
  hostnames:
    - grafana.zarantonello.net
  parentRefs:
    - name: http-prem-1
      namespace: cilium
  rules:
    - backendRefs:
        - name: http
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
