configs:
  blocky:
    file: ./config.yml

networks:
  alloy_default:
    external: true

services:
  blocky:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    configs:
      - source: blocky
        target: /app/config.yml
    # Host specific configuration for port bindings.
    extends:
      file: ${HOSTNAME}.docker-compose.yml
      service: blocky
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - blocky
        - healthcheck
    image: ghcr.io/0xerr0r/blocky:0.25@sha256:347f8c6addc1775ef74b83dfc609c28436a67f812ef0ee7e2602569dc0e56cd1
    labels:
      metrics.job: blocky
      metrics.port: 8080
    networks:
      - alloy_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 21575:21575
