configs:
  blocky:
    file: ./config.yml

networks:
  vmagent_default:
    external: true

services:
  blocky:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    configs:
      - source: blocky
        target: /app/config.yml
    # Host specific configuration for port bindings.
    extends:
      file: ${HOSTNAME}.docker-compose.yml
      service: blocky
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - blocky
        - healthcheck
    image: ghcr.io/0xerr0r/blocky:0.24@sha256:9a82e0235c52ef3048586f8006add06e52132adaae70d02f980569dae16421a2
    labels:
      victoriametrics.job: blocky
      victoriametrics.port: 8080
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 21575:21575
