services:
  woodpecker-agent:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      WOODPECKER_HOSTNAME: $HOSTNAME
      WOODPECKER_SERVER: ci-grpc-prem-0.zarantonello.dev:80
    # Add to docker group to use the docker socket.
    group_add:
      - "992"
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - woodpecker-agent
        - ping
      timeout: 5s
    image: docker.io/woodpeckerci/woodpecker-agent:v3.8.0@sha256:614d4d0fbd119c21e0d42a0dd3bd992e952c78c87251936b78ea1f7eda3e046b
    labels:
      monitoring.collect: true
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges=true
    user: 36307:36307
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
