# SETUP:
#
# Create a .env file with:
#
# - WOODPECKER_AGENT_SECRET

services:
  woodpecker-agent:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      WOODPECKER_SERVER: 100.99.201.25:80
    # Add to docker group to use the docker socket.
    group_add:
      - "992"
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - woodpecker-agent
        - ping
      timeout: 5s
    image: docker.io/woodpeckerci/woodpecker-agent:v3.5.0@sha256:576119c81e1e3043f1f19ddeaf94908d942f002d0d11f898016c208b6247f145
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 36307:36307
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
