apiVersion: v1
kind: PersistentVolume
metadata:
  name: outline-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100M
  local:
    path: /var/lib/rancher/k3s/volumes/outline-postgres-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - hz-0
