configs:
  alloy:
    file: ./config.alloy

networks:
  alloy_default:
    name: alloy_default

services:
  alloy:
    cap_drop:
      - ALL
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    configs:
      - source: alloy
        target: /etc/alloy/config.alloy
    extra_hosts:
      - hosts.docker.internal:host-gateway
    group_add:
      - "992"
    hostname: ${HOSTNAME}
    image: docker.io/grafana/alloy:v1.8.1@sha256:7790f6f7fbd8e4486b4b6c6fc6a7293a73605bb79aaa7f49003cb366943724f6
    labels:
      monitoring.collect: true
      monitoring.metrics.port: 12345
    networks:
      - alloy_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 58210:58210
    volumes:
      - $HOME/volumes/alloy:/var/lib/alloy
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 12345:12345

  node-exporter:
    cap_drop:
      - ALL
    command:
      - --path.rootfs=/host
    image: quay.io/prometheus/node-exporter:v1.9.0@sha256:c99d7ee4d12a38661788f60d9eca493f08584e2e544bbd3b3fca64749f86b848
    labels:
      monitoring.collect: true
      monitoring.metrics.port: 9100
    network_mode: host
    pid: host
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 3095:3095
    volumes:
      - /:/host:ro,rslave
