# SETUP:
#
# Create a .env file with:
#
# - TUNNEL_TOKEN

networks:
  traefik_default:
    external: true

services:
  cloudflared:
    cap_drop:
      - ALL
    command:
      - tunnel
      - run
    env_file: .env
    environment:
      NO_AUTOUPDATE: true
    image: docker.io/cloudflare/cloudflared:2024.12.0@sha256:1b92a01338a9a310cf5e1c7b77c61cce333e14117398814e4c124e4e9f7bbde2
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 17026:17026
