# Create a .end file with:
#
# TUNNEL_TOKEN=

name: cloudflared

networks:
  cloudflared:
    name: cloudflared

services:
  cloudflared:
    cap_drop:
      - ALL
    command:
      - tunnel
      - run
    env_file: .env
    environment:
      NO_AUTOUPDATE: true
    networks:
      - cloudflared
    image: docker.io/cloudflare/cloudflared:2024.10.0
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges=true
    user: 17026:17026
