# kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8

# SETUP:
#
# Create a .env file with:
#
# - TUNNEL_TOKEN

networks:
  default: {}

services:
  cloudflared:
    cap_drop:
      - ALL
    command:
      - tunnel
      - run
    env_file: .env
    environment:
      NO_AUTOUPDATE: true
    image: docker.io/cloudflare/cloudflared:2024.11.0@sha256:2c78df02e1f23ab19d4c636921f05b9ebec163b887e946f98e22e56254a5540f
    networks:
      - default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 17026:17026
