# kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8

# SETUP:
#
# Create a .env file with:
#
# - TUNNEL_TOKEN

networks:
  default:
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"

services:
  cloudflared:
    cap_drop:
      - ALL
    command:
      - tunnel
      - run
    env_file: .env
    environment:
      NO_AUTOUPDATE: true
    image: docker.io/cloudflare/cloudflared:2024.11.1@sha256:665dda65335e35a782ed9319aa63e8404f88b34d2644d30adf3e91253604ffa0
    networks:
      - default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 17026:17026
