# kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8

# Create a .env file with:
#
# TUNNEL_TOKEN=

name: cloudflared

networks:
  cloudflared:
    name: cloudflared

services:
  cloudflared:
    cap_drop:
      - ALL
    command:
      - tunnel
      - run
    env_file: .env
    environment:
      NO_AUTOUPDATE: true
    image: docker.io/cloudflare/cloudflared:2024.10.0
    networks:
      - cloudflared
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 17026:17026
