# kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8

# Create .env file with:
#
# CF_API_TOKEN=

configs:
  caddyfile:
    file: configs/${HOSTNAME}.Caddyfile

networks:
  caddy:
    name: caddy

services:
  caddy:
    build: .
    # kics-scan ignore-block
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    env_file: .env
    networks:
      - caddy
    # kics-scan ignore-block
    ports:
      - 443:443/tcp
      - 443:443/udp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /config?uid=41380,gid=41380
    user: 41380:41380
    volumes:
      - data:/data

volumes:
  data: {}
