apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
  - envs:
      - generated/configs/vaultwarden.env
    name: vaultwarden-env
kind: Kustomization
namespace: vaultwarden
resources:
  - deployments/vaultwarden.yaml
  - namespace.yaml
  - persistent-volume-claims/vaultwarden-data.yaml
  - persistent-volumes/vaultwarden-data.yaml
  - service-accounts/default.yml
  - services/web-ui.yaml
secretGenerator:
  - envs:
      - generated/secrets/vaultwarden.env
    name: vaultwarden-env
