apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - helm-releases/cert-manager.yaml
  - helm-repositories/cert-manager.yaml
  - namespace.yaml
  - service-accounts/default.yml
