# SETUP:
#
# Create a .env file with:
#
# - POSTGRES_DB
# - POSTGRES_PASSWORD
# - POSTGRES_USER
# - NEXTCLOUD_ADMIN_USER
# - NEXTCLOUD_ADMIN_PASSWORD
#
# Additional configuration can be edited by running
# `docker compose exec -it nextcloud vi /var/www/html/config/config.php`.

configs:
  caddyfile:
    file: Caddyfile

networks:
  traefik_default:
    external: true

services:
  caddy:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    image: docker.io/library/caddy:2.8.4-alpine@sha256:fea55ae5ce2e5c07dd3d592cc34862504075d55d505d731cdc2a3f051d70d39c
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.rule: Host(`cloud.zarantonello.dev`)
      traefik.http.services.nextcloud.loadbalancer.server.port: 3000
    networks:
      - default
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /config:uid=52892,gid=52892
      - /data:uid=52892,gid=52892
    user: 52892:52892
    volumes:
      - nextcloud:/var/www/html:ro

  nextcloud:
    cap_drop:
      - ALL
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.zarantonello.dev
      OVERWRITECLIURL: http://caddy:3000
      OVERWRITEHOST: cloud.zarantonello.dev
      OVERWRITEPROTOCOL: https
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    image: docker.io/library/nextcloud:30.0.4-fpm-alpine@sha256:83b566bcdac262db029f220401684c8b301fe662d39c922515f1867d190a6e2a
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=82,gid=82
    user: 82:82
    volumes:
      - data:/var/www/html/data
      - nextcloud:/var/www/html

  nextcloud_cron:
    depends_on:
      nextcloud:
        condition: service_started
    entrypoint:
      - sh
      - -c
      - while true ; do php -f /var/www/html/cron.php && sleep 300 ; done
    extends:
      service: nextcloud

  # The first time nextcloud runs, it's normal that this service fails. Ensure
  # to install the notify push app inside nextcloud to make this work.

  nextcloud_notify_push:
    depends_on:
      nextcloud:
        condition: service_started
    entrypoint:
      - /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push
      - /var/www/html/config/config.php
    extends:
      service: nextcloud

  postgres:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      PGUSER: ${POSTGRES_USER}
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - pg_isready
      timeout: 5s
    image: docker.io/library/postgres:17.2-alpine@sha256:d37d2c160d34430877c802e5adc22824a2ad453499db9bab1a2ceb2be6c1a46f
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=70,gid=70
      - /var/run/postgresql:uid=70,gid=70
    # User has to be 70, otherwise the container tries to chown the postgres
    # volume but fails due to insufficient permissions.
    user: 70:70
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    cap_drop:
      - ALL
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 5s
    image: docker.io/library/redis:7.4.2-alpine@sha256:99f9a7e68297e7b196a6e7b59437b30b50b0328a9d725ec144403f552fa66afb
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 24056:24056
    volumes:
      - redis:/data

volumes:
  data: {}
  nextcloud: {}
  postgres: {}
  redis: {}
