# kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8

# SETUP:
#
# Connect to the web interface and follow instructions from there.

networks:
  traefik_default:
    external: true

services:
  adguard:
    # kics-scan ignore-block
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    image: docker.io/adguard/adguardhome:v0.107.54@sha256:ec59d9d8d083b74620f827879bee7ad88621f96bc0c4347c84c176ffa349484c
    labels:
      traefik.enable: true
      traefik.http.routers.adguard.rule: Host(`dns.zarantonello.dev`)
      traefik.http.services.adguard.loadbalancer.server.port: 3000
    networks:
      - traefik_default
    ports:
      - 100.106.32.89:53:1053/tcp
      - 100.106.32.89:53:1053/udp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 58442:58442
    volumes:
      - config:/opt/adguardhome/conf
      - data:/opt/adguardhome/work

volumes:
  config: {}
  data: {}
