name: adguard

services:
  adguard:
    image: docker.io/adguard/adguardhome:v0.107.52@sha256:d16cc7517ab96f843e7f8bf8826402dba98f5e6b175858920296243332391589
    ports:
      - 3000:3000
      - 53:53/tcp
      - 53:53/udp
    read_only: true
    restart: always
    volumes:
      - config:/opt/adguardhome/conf
      - data:/opt/adguardhome/work

volumes:
  config: {}
  data: {}
