# kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8

# SETUP:
#
# Connect to the web interface and follow instructions from there.

services:
  adguard:
    # kics-scan ignore-block
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    image: docker.io/adguard/adguardhome:v0.107.53@sha256:d9c512051141e6a617d773f16cdf6782c178464c6e766acf9fe63482a171f95c
    network_mode: host
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 58442:58442
    volumes:
      - config:/opt/adguardhome/conf
      - data:/opt/adguardhome/work

volumes:
  config: {}
  data: {}
