configs:
  garage:
    file: ./${HOSTNAME}.garage.toml

networks:
  traefik_default:
    external: true
  alloy_default:
    external: true

services:
  garage:
    cap_drop:
      - ALL
    configs:
      - source: garage
        target: /etc/garage.toml
    env_file: .env
    # Host specific configuration for volumes and http host.
    extends:
      file: docker-compose.${HOSTNAME}.yml
      service: garage
    image: docker.io/dxflrs/garage:v1.1.0
    labels:
      monitoring.collect: true
      monitoring.port: 3903
      traefik.enable: true
      traefik.http.routers.garage-s3.entrypoints: http,https,cloudflared
      traefik.http.routers.garage-s3.service: garage-s3
      traefik.http.services.garage-s3.loadbalancer.server.port: 3900
    networks:
      - alloy_default
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 18781:18781
