services:
  garage:
    build: .
    cap_drop:
      - ALL
    env_file: .env
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - wget
        - -q
        - -O
        - /dev/stdout
        - http://localhost:3903/health
    labels:
      monitoring.collect: true
      monitoring.metrics.port: 3903
      traefik.enable: true
    networks:
      - alloy_default
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 18781:18781
