metadata_dir = "/var/lib/garage/meta"
data_dir = [
  { path = "/var/lib/garage/data/1", capacity = "" },
  { path = "/var/lib/garage/data/2", capacity = "" },
  { path = "/var/lib/garage/data/3", capacity = "" },
  { path = "/var/lib/garage/data/4", capacity = "" },
]
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 1
consistency_mode = "consistent"

rpc_bind_addr = "127.0.0.1:3901"
rpc_public_addr = "127.0.0.1:3901"

[s3_api]
s3_region = "default"
api_bind_addr = "[::]:3900"

[admin]
api_bind_addr = "[::]:3903"
