configs:
  traefik:
    file: ./traefik.yml

networks:
  alloy_default:
    external: true
  traefik_default:
    name: traefik_default

services:
  traefik:
    cap_drop:
      - ALL
    configs:
      - source: traefik
        target: /etc/traefik/traefik.yml
    env_file: .env
    extends:
      file: docker-compose.${HOSTNAME}.yml
      service: traefik
    group_add:
      - "992"
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - traefik
        - healthcheck
      timeout: 5s
    image: docker.io/library/traefik:v3.5.0@sha256:4e7175cfe19be83c6b928cae49dde2f2788fb307189a4dc9550b67acf30c11a5
    labels:
      monitoring.collect: true
      monitoring.metrics.port: 8082
    networks:
      alloy_default: {}
      # We need to set an alias for cloudflared to redirect to traefik.
      traefik_default:
        aliases:
          - traefik
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 51664:51664
    volumes:
      - traefik:/var/lib/traefik
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  traefik: {}
