# SETUP:
#
# Create .env file with:
#
# - CF_DNS_API_TOKEN
# - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL

configs:
  traefik:
    file: ./traefik.yml

networks:
  traefik_default:
    name: traefik_default
  vmagent_default:
    external: true

services:
  traefik:
    cap_drop:
      - ALL
    configs:
      - source: traefik
        target: /etc/traefik/traefik.yml
    env_file: .env
    extends:
      file: ${HOSTNAME}.docker-compose.yml
      service: traefik
    group_add:
      - "992"
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - traefik
        - healthcheck
      timeout: 5s
    image: docker.io/library/traefik:v3.3.5@sha256:104204dadedf5d1284f8ef8f97f705649ac81aa6f7a6c9abf13e2c59245b8abc
    labels:
      victoriametrics.job: traefik
      victoriametrics.port: 8082
    networks:
      traefik_default:
        aliases:
          - traefik
      vmagent_default: {}
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 51664:51664
    volumes:
      - $HOME/volumes/traefik-certificates:/var/lib/traefik/certificates
      - /var/run/docker.sock:/var/run/docker.sock
