apiVersion: v1
kind: PersistentVolume
metadata:
  name: mimir-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10G
  local:
    path: /var/lib/rancher/k3s/volumes/mimir-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - x555sj.srv.zarantonello.dev
