services:
  blocky:
    ports:
      - "[fd7a:115c:a1e0::b001:387b]:53:53/tcp"
      - "[fd7a:115c:a1e0::b001:387b]:53:53/udp"
      - 100.125.56.122:53:53/tcp
      - 100.125.56.122:53:53/udp
      # docker containers use localhost. Disable systemd-resolved on systems
      # where it is running.
      - 127.0.0.1:53:53/udp
      - 127.0.0.1:53:53/tcp
