networks:
  traefik_default:
    external: true
  vmagent_default:
    external: true

services:
  victoriametrics:
    cap_drop:
      - ALL
    command:
      - -retentionPeriod=90d
    image: docker.io/victoriametrics/victoria-metrics:v1.112.0-scratch@sha256:5ba561b493758a25f2d6ab687f3d9374e46050c61b6c1b3b7b0c99188f3e8b55
    labels:
      traefik.enable: true
      traefik.http.routers.victoriametrics.entrypoints: http
      traefik.http.routers.victoriametrics.rule: Host(`victoriametrics.zarantonello.net`)
      traefik.http.services.victoriametrics.loadbalancer.server.port: 8428
      victoriametrics.job: victoriametrics
      victoriametrics.port: 8428
    networks:
      - traefik_default
      - vmagent_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 34866:34866
    volumes:
      - data:/victoria-metrics-data

volumes:
  data: {}
