apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
  - envs:
      - generated/configs/minio.env
    name: minio-env
kind: Kustomization
namespace: minio
resources:
  - deployments/minio.yaml
  - namespace.yaml
  - persistent-volume-claims/minio-data.yaml
  - persistent-volumes/minio-data.yaml
  - service-accounts/default.yaml
  - services/web-ui.yaml
  - services/s3.yaml
secretGenerator:
  - envs:
      - generated/secrets/minio.env
    name: minio-env
