networks:
  traefik_default:
    external: true

services:
  # kics-scan ignore-block
  chown-volumes:
    entrypoint:
      - sh
      - -c
      - chown -R 50788:50788 /var/lib/volumes/data /var/lib/volumes/database
    image: docker.io/library/busybox:1.37.0-musl@sha256:e95352f7c5174c96ffc684150c9d08fc3ba26ac2f37c613c398fd369e15a0789
    network_mode: none
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - data:/var/lib/volumes/data
      - database:/var/lib/volumes/database

  filebrowser:
    cap_drop:
      - ALL
    depends_on:
      chown-volumes:
        condition: service_completed_successfully
    environment:
      FB_BASE_URL: https://files.zarantonello.dev
      FB_DATABASE: /var/lib/filebrowser/database/db.sqlite
      FB_PORT: 3000
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - /healthcheck.sh
      timeout: 5s
    image: docker.io/filebrowser/filebrowser:v2.31.2@sha256:a4da9ca8364b0a1fc5dd36f7add92582bf673c0ae0bda8dd9bd13062c41d1715
    labels:
      traefik.enable: true
      traefik.http.routers.filebrowser.rule: Host(`files.zarantonello.dev`)
      traefik.http.services.filebrowser.loadbalancer.server.port: 3000
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 50788:50788
    volumes:
      - data:/srv
      - database:/var/lib/filebrowser/database

volumes:
  data: {}
  database: {}
