name: filebrowser

services:
  filebrowser:
    command:
      - -d
      - /database/db
    image: docker.io/filebrowser/filebrowser:v2.31.1@sha256:b9b0dcac8b20c01ed4777889c8ae6ff74443ed604e11e4b862d9f3068eeb9114
    ports:
      - 3002:80
    read_only: true
    restart: always
    volumes:
      - data:/srv
      - database:/database

volumes:
  data: {}
  database: {}
