name: filebrowser

networks:
  caddy:
    external: true

services:
  filebrowser:
    cap_drop:
      - ALL
    command:
      - --database=/database/db
      - --port=3000
    image: docker.io/filebrowser/filebrowser:v2.31.2@sha256:a4da9ca8364b0a1fc5dd36f7add92582bf673c0ae0bda8dd9bd13062c41d1715
    networks:
      caddy:
        aliases:
          - filebrowser
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 50788:50788
    volumes:
      - data:/srv
      - database:/database

volumes:
  data: {}
  database: {}
