name: filebrowser

services:
  filebrowser:
    command:
      - -d
      - /database/db
    image: docker.io/filebrowser/filebrowser:v2.31.2@sha256:a4da9ca8364b0a1fc5dd36f7add92582bf673c0ae0bda8dd9bd13062c41d1715
    ports:
      - 3002:80
    read_only: true
    restart: always
    volumes:
      - data:/srv
      - database:/database

volumes:
  data: {}
  database: {}
