networks:
  traefik_default:
    external: true

services:
  filebrowser:
    cap_drop:
      - ALL
    environment:
      FB_BASE_URL: https://files.zarantonello.dev
      FB_DATABASE: /var/lib/filebrowser/database/db.sqlite
      FB_PORT: 3000
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - /healthcheck.sh
      timeout: 5s
    image: docker.io/filebrowser/filebrowser:v2.31.2@sha256:a4da9ca8364b0a1fc5dd36f7add92582bf673c0ae0bda8dd9bd13062c41d1715
    labels:
      traefik.enable: true
      traefik.http.routers.filebrowser.rule: Host(`files.zarantonello.dev`)
      traefik.http.services.filebrowser.loadbalancer.server.port: 3000
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 50788:50788
    volumes:
      - data:/srv
      - database:/var/lib/filebrowser/database

volumes:
  data: {}
  database: {}
