apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: minio
      apps.zarantonello.dev/namespace: minio
  # Persistent volume cannot be read by 2 replicas.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: minio
        apps.zarantonello.dev/namespace: minio
    spec:
      containers:
        - args:
            - server
          envFrom:
            - configMapRef:
                name: minio-env
            - secretRef:
                name: minio-env
          image: quay.io/minio/minio:RELEASE.2025-02-18T16-25-55Z@sha256:1df91be8d6a6146001cd6be2569a12785a8ece583b511f56ebed08f1e65d3611
          name: minio
          ports:
            - containerPort: 9000
              name: http-s3
            - containerPort: 9001
              name: http-web-ui
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /data
              name: data
      enableServiceLinks: false
      securityContext:
        fsGroup: 43251
        runAsGroup: 43251
        runAsNonRoot: true
        runAsUser: 43251
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-data
