apiVersion: v1
kind: Service
metadata:
  name: minio-s3
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-s3
  selector:
    apps.zarantonello.dev/name: minio
    apps.zarantonello.dev/namespace: minio
