metadata_dir = "/var/lib/garage/metadata"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 1
consistency_mode = "consistent"

rpc_bind_addr = "127.0.0.1:3901"
rpc_public_addr = "127.0.0.1:3901"

[s3_api]
s3_region = "default"
api_bind_addr = "[::]:3900"

[admin]
api_bind_addr = "[::]:3903"
