# kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8

# SETUP:
#
# Create a .env file with
#
# - MINIO_ROOT_USER
# - MINIO_ROOT_PASSWORD

networks:
  caddy_default:
    external: true

services:
  minio:
    cap_drop:
      - ALL
    command:
      - server
    env_file: .env
    environment:
      - MINIO_VOLUMES=/mnt/disk1 /mnt/disk2 /mnt/disk3 /mnt/disk4
      - MINIO_STORAGE_CLASS_STANDARD=EC:1
      - MINIO_CONSOLE_ADDRESS=:9001
      - MINIO_BROWSER_REDIRECT_URL=https://minio.zarantonello.dev/minio/
    image: quay.io/minio/minio:RELEASE.2024-10-29T16-01-48Z-cpuv1@sha256:92f77ad56d46cbf1cf53432e79170d6c42c3f4cb328bde25d1c1371e04d4807b
    networks:
      caddy_default:
        aliases:
          - minio
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 29349:29349
    volumes:
      - /mnt/minio:/mnt:Z
