# Create a .env file with
#
# MINIO_ROOT_USER=
# MINIO_ROOT_PASSWORD=

name: minio

services:
  minio:
    cap_drop:
      - ALL
    command:
      - server
    env_file: .env
    environment:
      - MINIO_VOLUMES=/mnt/disk1 /mnt/disk2 /mnt/disk3 /mnt/disk4
      - MINIO_STORAGE_CLASS_STANDARD=EC:1
      - MINIO_CONSOLE_ADDRESS=:9001
      - MINIO_BROWSER_REDIRECT_URL=https://minio.zarantonello.dev/minio/
    image: quay.io/minio/minio:RELEASE.2024-10-02T17-50-41Z-cpuv1@sha256:49599b999e2415e854b7038c0d691be02011389c13340399077871c89cd75763
    ports:
      - 9000:9000
      - 9001:9001
    read_only: true
    restart: always
    user: 29349:29349
    volumes:
      - /mnt/minio:/mnt:Z
