apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: mimir
      apps.zarantonello.dev/namespace: monitoring
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: mimir
        apps.zarantonello.dev/namespace: monitoring
        monitoring.zarantonello.dev/job: mimir
        monitoring.zarantonello.dev/port: "8080"
    spec:
      containers:
        - args:
            - -config.expand-env=true
            - -config.file=/etc/mimir/mimir.yaml
          envFrom:
            - secretRef:
                name: mimir-s3-credentials
          image: docker.io/grafana/mimir:2.15.0@sha256:85f55510e0d348140db06566659193a96bf2b2695205d44fc1092092b937e9a0
          name: mimir
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/mimir
              name: mimir-config
            - mountPath: /var/tmp/mimir
              name: mimir-tmp
            - mountPath: /var/lib/mimir
              name: mimir-data
      enableServiceLinks: false
      securityContext:
        fsGroup: 29201
        runAsGroup: 29201
        runAsNonRoot: true
        runAsUser: 29201
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - configMap:
            name: mimir
          name: mimir-config
        - emptyDir: {}
          name: mimir-tmp
        - name: mimir-data
          persistentVolumeClaim:
            claimName: mimir-data
