apiVersion: v1
kind: Service
metadata:
  name: blocky-dns
spec:
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
  selector:
    apps.zarantonello.dev/name: blocky
    apps.zarantonello.dev/namespace: blocky
  type: LoadBalancer
