apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/ips: 100.64.0.1
    lbipam.cilium.io/sharing-cross-namespace: "*"
    lbipam.cilium.io/sharing-key: hetz-0-tailscale
  name: dns
spec:
  clusterIP: 10.96.0.11
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
  selector:
    apps.zarantonello.dev/name: blocky
    apps.zarantonello.dev/namespace: blocky
  type: LoadBalancer
