# SETUP:
#
# Create a .env file with:
#
# - NEXTCLOUD_ADMIN_USER
# - NEXTCLOUD_ADMIN_PASSWORD
# - POSTGRES_DB
# - POSTGRES_PASSWORD
# - POSTGRES_USER
#
# Additional configuration can be applied by running
# `docker compose exec -it nextcloud vi /var/www/html/config/config.php`.

configs:
  caddyfile:
    file: Caddyfile

networks:
  traefik_default:
    external: true

services:
  caddy:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    image: docker.io/library/caddy:2.9.1-alpine@sha256:b60636634fd2aebaf9460cf60997ad83aad6b139318d5713e2b78a60f52b139c
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.entrypoints: cloudflared
      traefik.http.routers.nextcloud.rule: Host(`cloud.zarantonello.dev`)
      traefik.http.services.nextcloud.loadbalancer.server.port: 3000
    networks:
      - default
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /config:uid=52892,gid=52892
      - /data:uid=52892,gid=52892
    user: 52892:52892
    volumes:
      - nextcloud:/var/www/html:ro

  nextcloud:
    cap_drop:
      - ALL
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.zarantonello.dev
      OVERWRITECLIURL: http://caddy:3000
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    image: docker.io/library/nextcloud:30.0.4-fpm-alpine@sha256:cc6a89eed5e5b24bbfb4f40b6eda77afd0b0abab175db29d2ef27c26885cbce7
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=82,gid=82
    user: 82:82
    volumes:
      - config:/var/www/html/config
      - data:/var/www/html/data
      - nextcloud:/var/www/html

  # Recurrent job that runs every 5 minutes.
  nextcloud-cron:
    depends_on:
      nextcloud:
        condition: service_started
    entrypoint:
      - sh
      - -c
      - while true ; do php -f /var/www/html/cron.php ; sleep 300 ; done
    extends:
      service: nextcloud

  # The first time nextcloud runs, it's normal that this service fails. Ensure
  # to install the notify push app inside nextcloud to make this work.
  nextcloud-notify-push:
    depends_on:
      nextcloud:
        condition: service_started
    entrypoint:
      - /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push
      - /var/www/html/config/config.php
    extends:
      service: nextcloud
    labels:
      traefik.enable: true
      traefik.http.middlewares.nextcloudNotifyPushStripPrefix.stripPrefix.prefixes: /push
      traefik.http.routers.nextcloud-notify-push.entrypoints: http
      traefik.http.routers.nextcloud-notify-push.middlewares: nextcloudNotifyPushStripPrefix@docker
      traefik.http.routers.nextcloud-notify-push.rule: Host(`cloud.zarantonello.dev`) && PathPrefix(`/push`)
      traefik.http.services.nextcloud-notify-push.loadbalancer.server.port: 7867
    networks:
      - default
      - traefik_default

  postgres:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      PGUSER: ${POSTGRES_USER}
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - pg_isready
      timeout: 5s
    image: docker.io/library/postgres:17.2-alpine@sha256:0bcc5bbbb2aa9c9b4c6505845918c7eb55d783cf5c1f434fac33012579fb149d
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=70,gid=70
      - /var/run/postgresql:uid=70,gid=70
    # User has to be 70, otherwise the container tries to chown the postgres
    # volume but fails due to insufficient permissions.
    user: 70:70
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    cap_drop:
      - ALL
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 5s
    image: docker.io/library/redis:7.4.2-alpine@sha256:1bf97f21f01b0e7bd4b7b34a26d3b9d8086e41e70c10f262e8a9e0b49b5116a0
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 24056:24056
    volumes:
      - redis:/data

volumes:
  config: {}
  data: {}
  nextcloud: {}
  postgres: {}
  redis: {}
