# kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8

# SETUP:
#
# Create a .env file with:
#
# POSTGRES_DB=
# POSTGRES_PASSWORD=
# POSTGRES_USER=
#
# Only the first time, run `docker compose create` to create volumes but don't 
# start containers. Then run `chown -R 82:82 /var/lib/docker/volumes/nextcloud_data/ _data`
# and after that `docker compose up -d`.
#
# Additional configuration can be done by running
# `docker compose exec -it nextcloud vi /var/www/html/config/config.php`.

# Refer to `../caddy/configs/x555sj.Caddyfile` for the php-fpm config.

networks:
  caddy_default:
    external: true
  default: {}

services:
  nextcloud:
    cap_drop:
      - ALL
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    image: docker.io/library/nextcloud:30.0.1-fpm-alpine@sha256:b6d31dfc4c47008b70ae6ca7235a3dc90e5343e69c1d61dff7f27b842e8e3876
    networks:
      caddy_default:
        aliases:
          - nextcloud
      default: {}
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 82:82
    volumes:
      - data:/var/www/html/data
      - nextcloud:/var/www/html
  postgres:
    cap_drop:
      - ALL
    env_file: .env
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - pg_isready
      timeout: 5s
    image: docker.io/library/postgres:17.0-alpine@sha256:14195b0729fce792f47ae3c3704d6fd04305826d57af3b01d5b4d004667df174
    networks:
      - default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=70,gid=70
      - /var/run/postgresql:uid=70,gid=70
    user: 70:70
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    cap_drop:
      - ALL
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 5s
    image: docker.io/library/redis:7.4.1-alpine@sha256:de13e74e14b98eb96bdf886791ae47686c3c5d29f9d5f85ea55206843e3fce26
    networks:
      - default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /data:uid=9243,gid=9243
    user: 9243:9243

volumes:
  data: {}
  nextcloud: {}
  postgres: {}
