apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-machine-learning-cache
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1G
  local:
    path: /var/mnt/local-storage/immich-machine-learning-cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - srv-0-cor-home
