apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
resources:
  - deployments/cloudflared.yaml
  - namespace.yaml
  - service-accounts/default.yaml
secretGenerator:
  - envs:
      - generated/secrets/cloudflared.env
    name: cloudflared-env
