apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - git-repositories/github-iac-manifests.yaml
  - kustomizations/github-iac-manifests.yaml
  - namespace.yaml
  - service-accounts/default.yml
