# SETUP:
#
# Connect to the web interface and follow instructions from there.

networks:
  traefik_default:
    external: true

services:
  adguard:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    image: docker.io/adguard/adguardhome:v0.107.55@sha256:2979cc78a28aceb77f90980a5440578dbb7bc406dffe261e9ae402750193bde0
    labels:
      traefik.enable: true
      traefik.http.routers.adguard.rule: Host(`dns.zarantonello.dev`)
      traefik.http.services.adguard.loadbalancer.server.port: 3000
    networks:
      - traefik_default
    ports:
      - 53:1053/tcp
      - 53:1053/udp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 58442:58442
    volumes:
      - config:/opt/adguardhome/conf
      - data:/opt/adguardhome/work

volumes:
  config: {}
  data: {}
