services:
  node-exporter:
    cap_drop:
      - ALL
    command:
      - --path.rootfs=/host
    image: quay.io/prometheus/node-exporter:v1.9.0@sha256:c99d7ee4d12a38661788f60d9eca493f08584e2e544bbd3b3fca64749f86b848
    labels:
      victoriametrics.job: node-exporter
      victoriametrics.port: 9100
    network_mode: host
    pid: host
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 3095:3095
    volumes:
      - /:/host:ro,rslave
