apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: default
spec:
  hostnames:
    - stalwart.zarantonello.dev
  parentRefs:
    - name: http-hetz-0
      namespace: cilium
  rules:
    - backendRefs:
        - name: http
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
