# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - pip install --root-user-action=ignore --progress-bar=off "commitizen==$COMMITIZEN_VERSION"
      - cz check --message "$CI_COMMIT_MESSAGE"
    environment:
      # renovate: datasource=pypi depName=commitizen versioning=pep440
      COMMITIZEN_VERSION: 3.30.1
    image: docker.io/library/python:3.13.0-alpine@sha256:d4daf858ce04f8e6f9a3f73d036f7a8dbb3b9541dccdb87e93993589449c5b9e
    name: check-commitizen
    volumes:
      - wp-cache_global_pip:/root/.cache/pip

when:
  - event: pull_request
