# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - woodpecker-cli lint
    image: docker.io/woodpeckerci/woodpecker-cli:v2.7.3-alpine@sha256:0a71a2c8b9761846c42a5ad5731564b3ee7ecb26ddb03f344e0f1505fa09a11d
    name: check-woodpecker-cli

when:
  - event: pull_request
