# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - bun x "markdownlint-cli2@$MARKDOWNLINT_CLI2_VERSION" **/*.md **/*.mdx
    environment:
      # renovate: datasource=npm depName=markdownlint-cli2 versioning=npm
      MARKDOWNLINT_CLI2_VERSION: 0.15.0
    image: docker.io/oven/bun:1.1.34-slim@sha256:21fd0a62420d24ad6d0b2e2d82af4824d2fa24942f34f3bca539e07d149c5770
    name: check-markdownlint-cli2
    volumes:
      - wp-cache_global_bun:/root/.bun/install/cache/

when:
  - event: pull_request
