# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - woodpecker-cli lint
    image: docker.io/woodpeckerci/woodpecker-cli:v2.7.2-alpine@sha256:6d50d297d0ea89d8b2d73d5f15511f521298aa2e1780faafa415540064e1d59f
    name: check-woodpecker-cli

when:
  - event: pull_request
