# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - pip install --root-user-action=ignore --progress-bar=off "yamllint==$YAMLLINT_VERSION"
      - yamllint .
    environment:
      # renovate: datasource=pypi depName=yamllint versioning=pep440
      YAMLLINT_VERSION: 1.35.1
    image: docker.io/library/python:3.13.0-alpine@sha256:9dbfed76969ce780f827f9e00e8454a04a6fbef753a478bc7586223e790defd0
    name: check-yamllint
    volumes:
      - wp-cache_global_pip:/root/.cache/pip

when:
  - event: pull_request
