apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: ollama
      apps.zarantonello.dev/namespace: ollama
  # Persistent volume cannot be read by 2 replicas.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: ollama
        apps.zarantonello.dev/namespace: ollama
    spec:
      containers:
        - image: docker.io/ollama/ollama:0.11.10@sha256:a5409cb903d30f9cd67e9f430dd336ddc9274e16fd78f75b675c42065991b4fd
          name: ollama
          ports:
            - containerPort: 11434
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /.ollama
              name: data
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: srv-0-cor-home
      securityContext:
        fsGroup: 18385
        runAsGroup: 18385
        runAsNonRoot: true
        runAsUser: 18385
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
