apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: ollama
      apps.zarantonello.dev/namespace: ollama
  # Persistent volume cannot be read by 2 replicas.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: ollama
        apps.zarantonello.dev/namespace: ollama
    spec:
      containers:
        - env:
            # Pulling models makes the node become unresponsive and when the
            # pod is restarted upload progress would be lost.
            - name: OLLAMA_NOPRUNE
              value: "true"
          image: docker.io/ollama/ollama:0.11.4@sha256:be17b353bf3cfab0b6980530284e64716a57589ed753a82d9a6a2a5fa9a61a31
          name: ollama
          ports:
            - containerPort: 11434
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /.ollama
              name: data
      enableServiceLinks: false
      securityContext:
        runAsGroup: 18385
        runAsNonRoot: true
        runAsUser: 18385
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
