configs:
  grafana:
    file: ./grafana.ini

networks:
  alloy_default:
    external: true
  traefik_default:
    external: true

services:
  grafana:
    cap_drop:
      - ALL
    configs:
      - source: grafana
        target: /etc/grafana/grafana.ini
    env_file: .env
    environment:
      GF_INSTALL_PLUGINS: victoriametrics-logs-datasource,victoriametrics-metrics-datasource
    image: docker.io/grafana/grafana:12.1.1@sha256:a1701c2180249361737a99a01bc770db39381640e4d631825d38ff4535efa47d
    labels:
      monitoring.collect: true
      monitoring.metrics.port: 3000
      traefik.enable: true
      traefik.http.routers.grafana.entrypoints: https
      traefik.http.routers.grafana.rule: Host(`grafana.zarantonello.net`)
      traefik.http.services.grafana.loadbalancer.server.port: 3000
    networks:
      - default
      - traefik_default
      - alloy_default
    restart: always
    security_opt:
      - no-new-privileges=true
    user: 31904:31904
    volumes:
      - ./provisioning:/etc/grafana/provisioning:ro
      - $HOME/volumes/grafana:/var/lib/grafana
