# kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8

# SETUP:
#
# Create .env file with:
#
# - CF_API_TOKEN

configs:
  caddyfile:
    file: configs/${HOSTNAME}.Caddyfile

services:
  caddy:
    build: .
    # kics-scan ignore-block
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    depends_on:
      chown-volumes:
        condition: service_completed_successfully
    env_file: .env
    # kics-scan ignore-block
    ports:
      - 443:443/tcp
      - 443:443/udp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /config:uid=41380,gid=41380
    user: 41380:41380
    volumes:
      - data:/data

  # kics-scan ignore-block
  chown-volumes:
    entrypoint:
      - sh
      - -c
      - chown -R 41380:41380 /volumes/data
    image: docker.io/library/busybox:1.37.0-musl@sha256:37ccc05112d0a7162b605c375f5c0f5cfbc6e6c4fc8030ead6ae26a18c28a542
    network_mode: none
    read_only: true
    restart: "no"
    security_opt:
      - no-new-privileges:true
    user: 0:0
    volumes:
      - data:/volumes/data

volumes:
  data: {}
