apiVersion: v1
kind: Service
metadata:
  name: web-ui
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-web-ui
  selector:
    apps.zarantonello.dev/name: minio
    apps.zarantonello.dev/namespace: minio
