networks:
  alloy_default:
    external: true
  traefik_default:
    external: true

services:
  postgres:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      # Configures the user used for healthchecking.
      PGUSER: ${POSTGRES_USER}
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - pg_isready
      timeout: 5s
    image: docker.io/library/postgres:17.5-alpine@sha256:fbe21607052bb5c298674f2fd8cf044a63aa3ddf50b81627f894f91f40f50bcb
    labels:
      monitoring.collect: true
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=70,gid=70
      - /var/run/postgresql:uid=70,gid=70
    # User has to be 70, otherwise the container tries to chown the postgres
    # volume but fails due to insufficient permissions.
    user: 70:70
    volumes:
      - $HOME/volumes/woodpecker/postgres:/var/lib/postgresql/data
      - $HOME/volumes/woodpecker/postgres-dumps:/var/lib/postgresql/dumps

  woodpecker-server:
    cap_drop:
      - ALL
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      WOODPECKER_DATABASE_DATASOURCE: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      WOODPECKER_DATABASE_DRIVER: postgres
      WOODPECKER_ENVIRONMENT: CI_VOLUMES_DIR:${HOME}/volumes/woodpecker/agent
      WOODPECKER_GITHUB: true
      WOODPECKER_HOST: https://ci.zarantonello.dev
      WOODPECKER_METRICS_SERVER_ADDR: :9001
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - woodpecker-server
        - ping
      timeout: 5s
    image: docker.io/woodpeckerci/woodpecker-server:v3.8.0@sha256:40bbd034462ec370d98078fbc31b50f951ca44cc02630eb22cd35d48afc3f037
    labels:
      monitoring.collect: true
      monitoring.metrics.port: 9001
      traefik.enable: true
      traefik.http.routers.woodpecker-grpc.entrypoints: http
      traefik.http.routers.woodpecker-grpc.rule: Host(`ci-grpc-prem-0.zarantonello.dev`)
      traefik.http.routers.woodpecker-grpc.service: woodpecker-grpc
      traefik.http.routers.woodpecker-http.entrypoints: cloudflared
      traefik.http.routers.woodpecker-http.rule: Host(`ci.zarantonello.dev`)
      traefik.http.routers.woodpecker-http.service: woodpecker-http
      traefik.http.services.woodpecker-grpc.loadbalancer.server.port: 9000
      traefik.http.services.woodpecker-grpc.loadbalancer.server.scheme: h2c
      traefik.http.services.woodpecker-http.loadbalancer.server.port: 8000
    networks:
      - alloy_default
      - default
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 4518:4518
