networks:
  alloy_default:
    external: true
  traefik_default:
    external: true

services:
  woodpecker-server:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      WOODPECKER_ENVIRONMENT: CI_VOLUMES_DIR:${HOME}/volumes/woodpecker-agent
      WOODPECKER_GITHUB: true
      WOODPECKER_HOST: https://ci.zarantonello.dev
      WOODPECKER_METRICS_SERVER_ADDR: :9001
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - woodpecker-server
        - ping
      timeout: 5s
    image: docker.io/woodpeckerci/woodpecker-server:v3.6.0@sha256:29b94e80f8f0fe9249a3ec6a0ed5c92d5dbabc7d10896ba85c970023a54eb09c
    labels:
      monitoring.collect: true
      monitoring.metrics.port: 9001
      traefik.enable: true
      traefik.http.routers.woodpecker-grpc.entrypoints: http
      traefik.http.routers.woodpecker-grpc.rule: Host(`ci-grpc-prem-0.zarantonello.dev`)
      traefik.http.routers.woodpecker-grpc.service: woodpecker-grpc
      traefik.http.routers.woodpecker-http.entrypoints: cloudflared
      traefik.http.routers.woodpecker-http.rule: Host(`ci.zarantonello.dev`)
      traefik.http.routers.woodpecker-http.service: woodpecker-http
      traefik.http.services.woodpecker-grpc.loadbalancer.server.port: 9000
      traefik.http.services.woodpecker-grpc.loadbalancer.server.scheme: h2c
      traefik.http.services.woodpecker-http.loadbalancer.server.port: 8000
    networks:
      - traefik_default
      - alloy_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 4518:4518
    volumes:
      - $HOME/volumes/woodpecker-server:/var/lib/woodpecker
