networks:
  alloy_default:
    external: true
  traefik_default:
    external: true

services:
  cloudflared:
    cap_drop:
      - ALL
    command:
      - tunnel
      - run
    env_file: .env
    environment:
      NO_AUTOUPDATE: true
    image: docker.io/cloudflare/cloudflared:2025.6.1@sha256:175aee7e8b548f983f7e3b79ace217676d2a79255a73c074dacb491e59603679
    labels:
      monitoring.collect: true
      monitoring.metrics.port: 20241
    networks:
      - alloy_default
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 17026:17026
