apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy
rules:
  # Used by discovery.kubernetes blocks with role="pod". We don't wan't to
  # scrape services or ingresses because collecting metrics from behind any kind
  # of load balancer can lead to unexpected results.
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
