concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  check-commitizen:
    env:
      # renovate: datasource=pypi depName=commitizen versioning=pep440
      COMMITIZEN_VERSION: 4.8.4
      PR_TITLE: ${{ github.event.pull_request.title }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          cache: pip
      - run: pip install --root-user-action=ignore --progress-bar=off "commitizen==$COMMITIZEN_VERSION"
      - run: cz check --message "$PR_TITLE"

"on":
  pull_request:
    branches:
      - main
