concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  check-biome:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: biomejs/setup-biome@c016c38f26f2c4a6eb3662679143614a254263fd # v2
      - run: biome ci

"on":
  pull_request:
    branches:
      - main
