concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  check-hadolint:
    container: docker.io/hadolint/hadolint:v2.12.0-alpine@sha256:3c206a451cec6d486367e758645269fd7d696c5ccb6ff59d8b03b0e45268a199
    runs-on: ubuntu-24.04
    steps:
      - run: apk add --no-cache git
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # Find all dockerfiles in the repo.
      - run: |
          git ls-tree --name-only -r HEAD | grep -E "^(.+\/)?(.*[^\/\s]\.)?Dockerfile$" | while read -r f ; do
            echo "checking $f" && hadolint "$f"
          done

"on":
  pull_request:
    branches:
      - main
