concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  check-actionlint:
    container:
      image: docker.io/rhysd/actionlint:1.7.6@sha256:e3856d413f923accc4120884ff79f6bdba3dd53fd42884d325f21af61cc15ce0
      options: --user=0:0
    runs-on: ubuntu-24.04
    steps:
      - run: apk add --no-cache git
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: actionlint

"on":
  pull_request:
    branches:
      - main
