concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  check-commitizen:
    env:
      # renovate: datasource=pypi depName=commitizen versioning=pep440
      COMMITIZEN_VERSION: 3.31.0
      PR_TITLE: ${{ github.event.pull_request.title }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          cache: pip
      - run: pip install --root-user-action=ignore --progress-bar=off "commitizen==$COMMITIZEN_VERSION"
      - run: cz check --message "$PR_TITLE"

"on":
  pull_request:
    branches:
      - main
