concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  check-actionlint:
    container:
      image: docker.io/library/alpine:3.21.3
    runs-on: ubuntu-24.04
    steps:
      - run: apk add --no-cache git kustomize
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: kustomize build kubernetes

"on":
  pull_request:
    branches:
      - main
