concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  check-actionlint:
    container:
      image: docker.io/rhysd/actionlint:1.7.5@sha256:d1b3d067b912ea4cbf697750cee80f59114414365b916167b4c7b4cf9504ca9a
      options: --user=0:0
    runs-on: ubuntu-24.04
    steps:
      - run: apk add --no-cache git
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: actionlint

"on":
  pull_request:
    branches:
      - main
