concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  check-commitizen:
    env:
      # renovate: datasource=pypi depName=commitizen versioning=pep440
      COMMITIZEN_VERSION: 4.8.3
      PR_TITLE: ${{ github.event.pull_request.title }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          cache: pip
      - run: pip install --root-user-action=ignore --progress-bar=off "commitizen==$COMMITIZEN_VERSION"
      - run: cz check --message "$PR_TITLE"

"on":
  pull_request:
    branches:
      - main
