concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  check-kustomize:
    container:
      image: docker.io/library/alpine:3.21.3@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c
    runs-on: ubuntu-24.04
    steps:
      - run: apk add --no-cache git kustomize
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # Output to file to avoid saving too many logs to github actions.
      - run: kustomize build kubernetes --output cluster.yml

"on":
  pull_request:
    branches:
      - main
